/* ==== core/natures.js (généré depuis index.html) ==== */
const NATURES = [
 {name:'Hardi', plus:null, minus:null},
 {name:'Solo', plus:'atk', minus:'def'},
 {name:'Brave', plus:'atk', minus:'spe'},
 {name:'Rigide', plus:'atk', minus:'spa'},
 {name:'Mauvais', plus:'atk', minus:'spd'},
 {name:'Assuré', plus:'def', minus:'atk'},
 {name:'Sérieux', plus:null, minus:null},
 {name:'Relax', plus:'def', minus:'spe'},
 {name:'Malin', plus:'def', minus:'spa'},
 {name:'Lâche', plus:'def', minus:'spd'},
 {name:'Timide', plus:'spe', minus:'atk'},
 {name:'Pressé', plus:'spe', minus:'def'},
 {name:'Docile', plus:null, minus:null},
 {name:'Jovial', plus:'spe', minus:'spa'},
 {name:'Naïf', plus:'spe', minus:'spd'},
 {name:'Modeste', plus:'spa', minus:'atk'},
 {name:'Doux', plus:'spa', minus:'def'},
 {name:'Discret', plus:'spa', minus:'spe'},
 {name:'Pudique', plus:null, minus:null},
 {name:'Foufou', plus:'spa', minus:'spd'},
 {name:'Calme', plus:'spd', minus:'atk'},
 {name:'Gentil', plus:'spd', minus:'def'},
 {name:'Malpoli', plus:'spd', minus:'spe'},
 {name:'Prudent', plus:'spd', minus:'spa'},
 {name:'Bizarre', plus:null, minus:null}
];
