/* ==== moves/moves.js (généré depuis index.html) ==== */
const MOVES = {
  tackle:{pp:35,name:'Charge',type:'normal',cat:'phys',power:40,accuracy:1,desc:"Charge l'adversaire avec tout le corps."},
  quickattack:{pp:30,name:'Vive-Attaque',type:'normal',cat:'phys',power:35,accuracy:1,priority:1,desc:"Une charge fulgurante qui touche en premier."},
  headbutt:{pp:15,name:"Coup d'Boule",type:'normal',cat:'phys',power:45,accuracy:1,flinch:0.3,desc:"Un coup de tête puissant et imprévisible. Peut faire peur."},
  doubleedge:{pp:15,name:'Damoclès',type:'normal',cat:'phys',power:65,accuracy:1,recoil:0.25,desc:"Un assaut au corps perdu : l'attaquant subit aussi le contrecoup."},
  hyperfang:{pp:15,name:'Croc de Mort',type:'normal',cat:'phys',power:60,accuracy:0.9,flinch:0.1,desc:"Mord violemment l'adversaire avec ses incisives. Peut faire peur."},
  slash:{pp:20,name:'Tranche',type:'normal',cat:'phys',power:50,accuracy:1,desc:"Lacère l'adversaire avec griffes, queue ou faux."},
  bodyslam:{pp:15,name:'Plaquage',type:'normal',cat:'phys',power:55,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.3},desc:"Plaque l'adversaire de tout son poids. Peut paralyser."},
  swift:{pp:20,name:'Météores',type:'normal',cat:'spec',power:50,accuracy:1.0,desc:"Une pluie d'étoiles qui ne rate presque jamais."},
  hyperbeam:{pp:5,name:'Ultralaser',type:'normal',cat:'spec',power:85,desc:"Un rayon dévastateur qui épuise l'attaquant.",accuracy:0.9},

  ember:{pp:25,name:'Flammèche',type:'feu',cat:'spec',power:45,accuracy:1,secondaryStatus:{status:'brulure',chance:0.1},desc:"Projette une petite flamme sur l'adversaire. Peut brûler."},
  flamethrower:{pp:15,name:'Lance-Flammes',type:'feu',cat:'spec',power:70,accuracy:1,secondaryStatus:{status:'brulure',chance:0.1},desc:"Souffle un torrent de flammes intenses. Peut brûler."},
  fireblast:{pp:5,name:'Déflagration',type:'feu',cat:'spec',power:85,desc:"Un torrent de feu en forme d'étoile à 5 branches.",accuracy:0.85,secondaryStatus:{status:'brulure',chance:0.1}},
  firepunch:{pp:15,name:'Poing Feu',type:'feu',cat:'phys',power:55,accuracy:1,secondaryStatus:{status:'brulure',chance:0.1},desc:"Un coup de poing enflammé. Peut brûler."},

  watergun:{pp:25,name:"Pistolet à O",type:'eau',cat:'spec',power:45,accuracy:1,desc:"Projette un jet d'eau puissant."},
  hydropump:{pp:5,name:'Hydrocanon',type:'eau',cat:'spec',power:80,desc:"Une trombe d'eau d'une puissance colossale.",accuracy:0.8},
  surf:{pp:15,name:'Surf',type:'eau',cat:'spec',power:65,accuracy:1,bypassInvuln:['dive'],desc:"Une vague immense submerge le terrain. Touche même les cibles qui plongent."},
  bubblebeam:{pp:20,name:"Bulles d'O",type:'eau',cat:'spec',power:50,accuracy:1,secondaryBoost:{stat:'spe',stages:-1,chance:0.1},desc:"Tire un faisceau de bulles compressées. Peut réduire la Vitesse."},
  aquatail:{pp:10,name:'Hydroqueue',type:'eau',cat:'phys',power:60,accuracy:0.9,desc:"Frappe avec la queue comme une vague déferlante."},

  vinewhip:{pp:10,name:'Fouet Lianes',type:'plante',cat:'phys',power:45,accuracy:1,desc:"Fouette l'adversaire avec des lianes fines."},
  razorleaf:{pp:25,name:"Tranch'Herbe",type:'plante',cat:'phys',power:55,accuracy:0.95,desc:"Des feuilles tranchantes comme des lames."},
  solarbeam:{pp:10,name:'Lance-Soleil',type:'plante',cat:'spec',power:70,accuracy:1,charge:true,sunSkip:true,chargeMsg:'absorbe la lumière du soleil',desc:"Absorbe la lumière puis libère un rayon puissant au tour suivant (immédiat en plein soleil)."},
  megadrain:{pp:10,name:'Méga-Sangsue',type:'plante',cat:'spec',power:50,accuracy:1,drain:0.5,desc:"Aspire l'énergie vitale de l'adversaire pour se soigner."},
  gigadrain:{pp:5,name:'Giga Sangsue',type:'plante',cat:'spec',power:65,accuracy:1,drain:0.5,desc:"Draine une grande quantité d'énergie adverse pour se soigner."},
  leafblade:{pp:15,name:'Lame-Feuille',type:'plante',cat:'phys',power:65,accuracy:1,desc:"Une feuille aussi tranchante qu'une épée."},

  thundershock:{pp:30,name:'Éclair',type:'electrik',cat:'spec',power:45,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.1},desc:"Une faible décharge électrique surprend l'adversaire. Peut paralyser."},
  thunderbolt:{pp:15,name:'Tonnerre',type:'electrik',cat:'spec',power:70,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.1},desc:"Une puissante décharge électrique s'abat. Peut paralyser."},
  thunder:{pp:10,name:'Fatal-Foudre',type:'electrik',cat:'spec',power:85,bypassInvuln:['fly'],desc:"Un éclair surpuissant venu du ciel. Peut paralyser. Touche même les cibles en plein vol.",accuracy:0.75,secondaryStatus:{status:'paralysie',chance:0.3}},
  thunderpunch:{pp:15,name:'Poing Éclair',type:'electrik',cat:'phys',power:55,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.1},desc:"Un coup de poing chargé d'électricité. Peut paralyser."},
  discharge:{pp:15,name:"Coup d'jus",type:'electrik',cat:'spec',power:65,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.3},desc:"Décharge de l'électricité tout autour de soi. Peut paralyser."},

  icebeam:{pp:10,name:'Laser Glace',type:'glace',cat:'spec',power:70,accuracy:1,secondaryStatus:{status:'gel',chance:0.1},desc:"Un rayon de glace ultra-froid. Peut geler."},
  icepunch:{pp:15,name:'Poing Glace',type:'glace',cat:'phys',power:55,accuracy:1,secondaryStatus:{status:'gel',chance:0.1},desc:"Un coup de poing glacial. Peut geler."},
  blizzard:{pp:5,name:'Blizzard',type:'glace',cat:'spec',power:85,secondaryStatus:{status:'gel',chance:0.1},desc:"Une tempête de neige et de glace dévastatrice. Peut geler.",accuracy:0.75},
  icefang:{pp:15,name:'Crocs Givre',type:'glace',cat:'phys',power:55,accuracy:0.95,secondaryStatus:{status:'gel',chance:0.1},flinch:0.1,desc:"Mord l'adversaire avec des crocs gelés. Peut geler ou faire peur."},
  icywind:{pp:15,name:'Vent Glace',type:'glace',cat:'spec',power:45,accuracy:0.95,secondaryBoost:{stat:'spe',stages:-1,chance:1.0},desc:"Un vent glacial qui ralentit l'adversaire."},

  karatechop:{pp:25,name:'Poing Karaté',type:'combat',cat:'phys',power:50,accuracy:1,desc:"Un coup tranchant porté avec précision."},
  submission:{pp:20,name:'Sacrifice',type:'combat',cat:'phys',power:65,accuracy:0.8,recoil:0.25,desc:"Plaque l'adversaire au sol, mais le contrecoup blesse l'attaquant."},
  highjumpkick:{pp:20,name:'Pied Voltige',type:'combat',cat:'phys',power:70,recoil:0.33,desc:"Un saut suivi d'un coup de genou ; un échec blesserait l'attaquant.",accuracy:0.85},
  doublekick:{pp:30,name:'Double Pied',type:'combat',cat:'phys',power:55,accuracy:1,desc:"Deux coups de pied enchaînés rapidement."},
  crosschop:{pp:5,name:'Coup-Croix',type:'combat',cat:'phys',power:75,accuracy:0.8,desc:"Un coup croisé des deux bras, dur à éviter."},
  brickbreak:{pp:15,name:'Casse-Brique',type:'combat',cat:'phys',power:60,accuracy:1,desc:"Un coup tranchant capable de briser n'importe quoi."},

  sludge:{pp:20,name:'Détritus',type:'poison',cat:'spec',power:50,accuracy:1,secondaryStatus:{status:'poison',chance:0.3},desc:"Projette de la boue toxique sur l'adversaire. Peut empoisonner."},
  poisonsting:{pp:35,name:'Dard-Venin',type:'poison',cat:'phys',power:40,accuracy:1,secondaryStatus:{status:'poison',chance:0.2},desc:"Pique l'adversaire avec un dard empoisonné. Peut empoisonner."},
  acid:{pp:30,name:'Acide',type:'poison',cat:'spec',power:45,accuracy:1,secondaryBoost:{stat:'spd',stages:-1,chance:0.1},desc:"Asperge l'adversaire d'un liquide corrosif. Peut réduire la Défense Spéciale."},
  sludgebomb:{pp:10,name:'Bombe Toxik',type:'poison',cat:'spec',power:65,accuracy:1,secondaryStatus:{status:'poison',chance:0.3},desc:"Projette des amas de boue toxique immonde. Peut empoisonner."},
  poisonjab:{pp:20,name:'Direct Toxik',type:'poison',cat:'phys',power:60,accuracy:1,secondaryStatus:{status:'poison',chance:0.3},desc:"Transperce l'adversaire avec un membre empoisonné. Peut empoisonner."},

  dig:{pp:10,name:'Tunnel',type:'sol',cat:'phys',power:50,accuracy:1,charge:true,semiInvuln:'dig',chargeMsg:'creuse un tunnel sous terre',desc:"S'enfonce sous terre (esquive les attaques, sauf Séisme/Ampleur/Lame du Vide) puis surgit pour frapper au tour suivant."},
  earthquake:{pp:10,name:'Séisme',type:'sol',cat:'phys',power:75,accuracy:1,bypassInvuln:['dig'],desc:"Provoque un puissant séisme sous l'adversaire. Touche même les cibles sous terre."},
  bonemerang:{pp:10,name:'Osmerang',type:'sol',cat:'phys',power:55,accuracy:0.9,desc:"Lance un os qui frappe à l'aller et au retour."},
  mudshot:{pp:15,name:'Tir de Boue',type:'sol',cat:'spec',power:45,accuracy:0.95,secondaryBoost:{stat:'spe',stages:-1,chance:1.0},desc:"Projette une motte de boue sur l'adversaire et réduit sa Vitesse."},

  gust:{pp:35,name:'Tornade',type:'vol',cat:'spec',power:45,accuracy:1,bypassInvuln:['fly'],desc:"Bat des ailes pour créer une rafale de vent. Touche même les cibles en plein vol."},
  wingattack:{pp:35,name:'Cru-Ailes',type:'vol',cat:'phys',power:55,accuracy:1,desc:"Frappe l'adversaire avec des ailes largement déployées."},
  drillpeck:{pp:20,name:'Sonic-Pic',type:'vol',cat:'phys',power:65,accuracy:1,desc:"Un bec en vrille perfore l'adversaire."},
  hurricane:{pp:10,name:'Tempête Ailée',type:'vol',cat:'spec',power:70,accuracy:0.7,secondaryStatus:{status:'confusion',chance:0.3},desc:"Une tempête déchaînée emporte tout sur son passage. Peut confondre."},
  airslash:{pp:15,name:"Lame d'Air",type:'vol',cat:'spec',power:60,accuracy:0.95,flinch:0.3,desc:"Une lame d'air tranchante peut apeurer l'adversaire."},

  confusion:{pp:25,name:'Choc Mental',type:'psy',cat:'spec',power:45,accuracy:1,secondaryStatus:{status:'confusion',chance:0.1},desc:"Une attaque psychique légère mais déroutante. Peut rendre confus."},
  psychic:{pp:10,name:'Psyko',type:'psy',cat:'spec',power:75,accuracy:1,secondaryBoost:{stat:'spd',stages:-1,chance:0.1},desc:"Une puissante attaque télékinétique. Peut réduire la Défense Spéciale."},
  psybeam:{pp:20,name:'Rayon Psy',type:'psy',cat:'spec',power:55,accuracy:1,secondaryStatus:{status:'confusion',chance:0.1},desc:"Tire un rayon étrange qui perturbe l'esprit. Peut rendre confus."},
  zenheadbutt:{pp:15,name:"Psykoud'Boul",type:'psy',cat:'phys',power:55,accuracy:0.9,flinch:0.2,desc:"Un coup de tête chargé de pouvoir psychique. Peut faire peur."},
  extrasensory:{pp:20,name:'Extrasenseur',type:'psy',cat:'spec',power:60,accuracy:1,flinch:0.1,desc:"Une attaque psychique soudaine et surprenante. Peut faire peur."},

  leechlife:{pp:15,name:'Vampirisme',type:'insecte',cat:'phys',power:45,accuracy:1,drain:0.5,desc:"Aspire le sang de l'adversaire pour se soigner."},
  pinmissile:{pp:20,name:'Dard-Nuée',type:'insecte',cat:'phys',power:50,accuracy:0.95,desc:"Tire une volée d'aiguillons pointus."},
  megahorn:{pp:10,name:'Mégacorne',type:'insecte',cat:'phys',power:70,accuracy:0.85,desc:"Charge violemment avec une corne robuste."},
  bugbite:{pp:20,name:'Piqûre',type:'insecte',cat:'phys',power:45,accuracy:1,desc:"Mord vivement l'adversaire avec ses mandibules."},

  rockthrow:{pp:15,name:'Jet de Pierres',type:'roche',cat:'phys',power:45,accuracy:0.9,desc:"Soulève et lance des pierres sur l'adversaire."},
  rockslide:{pp:10,name:'Éboulement',type:'roche',cat:'phys',power:65,accuracy:0.9,flinch:0.3,desc:"De grosses roches s'écrasent sur l'adversaire. Peut faire peur."},
  stoneedge:{pp:5,name:'Lame de Roc',type:'roche',cat:'phys',power:75,desc:"Des pierres tranchantes aux angles redoutables.",accuracy:0.8},

  lick:{pp:30,name:'Léchouille',type:'fantome',cat:'phys',power:40,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.3},desc:"Lèche l'adversaire avec une langue spectrale. Peut paralyser."},
  shadowball:{pp:15,name:"Ball'Ombre",type:'fantome',cat:'spec',power:70,accuracy:1,secondaryBoost:{stat:'spd',stages:-1,chance:0.2},desc:"Projette une masse d'énergie spectrale. Peut réduire la Défense Spéciale."},
  nightshade:{pp:15,name:'Ombre Nocturne',type:'fantome',cat:'spec',power:55,accuracy:1,desc:"Fait apparaître une ombre terrifiante."},
  shadowclaw:{pp:15,name:'Griffe Ombre',type:'fantome',cat:'phys',power:60,accuracy:1,desc:"Une griffe tranchante venue d'une autre dimension."},

  dragonbreath:{pp:20,name:'Dracosouffle',type:'dragon',cat:'spec',power:50,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.3},desc:"Souffle une énergie féroce sur l'adversaire. Peut paralyser."},
  dragonclaw:{pp:15,name:'Dracogriffe',type:'dragon',cat:'phys',power:65,accuracy:1,desc:"De vastes griffes tranchent l'adversaire."},

  ironhead:{pp:15,name:'Tête de Fer',type:'acier',cat:'phys',power:65,accuracy:1,flinch:0.3,desc:"Un coup de tête recouvert d'acier étincelant. Peut faire peur."},
  steelwing:{pp:25,name:"Aile d'Acier",type:'acier',cat:'phys',power:50,accuracy:0.9,secondarySelfBoost:{stat:'def',stages:1,chance:0.1},desc:"Frappe avec des ailes durcies comme du métal. Peut booster sa Défense."},
  irondefense:{pp:15,name:'Mur de Fer',type:'acier',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:2}]},desc:"Durcit son corps pour booster fortement la Défense."},
  flashcannon:{pp:10,name:'Luminocanon',type:'acier',cat:'spec',power:70,accuracy:1,secondaryBoost:{stat:'spd',stages:-1,chance:0.1},desc:"Libère une lumière métallique aveuglante. Peut réduire la Défense Spéciale."},

  crunch:{pp:15,name:'Machouille',type:'tenebres',cat:'phys',power:65,accuracy:1,secondaryBoost:{stat:'def',stages:-1,chance:0.2},desc:"Mord avec des crocs redoutables. Peut réduire la Défense."},
  darkpulse:{pp:15,name:'Vibrobscur',type:'tenebres',cat:'spec',power:65,accuracy:1,flinch:0.2,desc:"Libère une onde de ténèbres pures et terrifiantes. Peut faire peur."},
  suckerpunch:{pp:5,name:'Coup Bas',type:'tenebres',cat:'phys',power:55,accuracy:1,priority:1,desc:"Une attaque sournoise qui surprend l'adversaire."},
  nightslash:{pp:15,name:'Tranche-Nuit',type:'tenebres',cat:'phys',power:60,accuracy:1,desc:"Lacère l'adversaire dès qu'une occasion se présente."},
  feintattack:{pp:20,name:'Feinte',type:'tenebres',cat:'phys',power:50,accuracy:1.0,desc:"Une attaque sournoise qui ne rate jamais sa cible."},

  /* ---- Nouvelles attaques Gen 1 ---- */
  scratch:{pp:35,name:'Griffe',type:'normal',cat:'phys',power:40,accuracy:1,desc:"Lacère l'adversaire avec des griffes acérées."},
  peck:{pp:35,name:'Picpic',type:'vol',cat:'phys',power:35,accuracy:1,desc:"Donne des coups de bec rapides à l'adversaire."},
  bite:{pp:25,name:'Morsure',type:'normal',cat:'phys',power:60,accuracy:1,flinch:0.3,desc:"Mord violemment l'adversaire. Peut faire peur."},
  bubble:{pp:30,name:'Écume',type:'eau',cat:'spec',power:40,accuracy:1,secondaryBoost:{stat:'spe',stages:-1,chance:0.1},desc:"Lance des bulles d'eau légères sur l'adversaire. Peut réduire la Vitesse."},
  stomp:{pp:20,name:'Écrasement',type:'normal',cat:'phys',power:55,accuracy:1,flinch:0.3,desc:"Écrase l'adversaire d'un pied lourd. Peut faire peur."},
  hornattack:{pp:25,name:"Koud'Korne",type:'normal',cat:'phys',power:65,accuracy:1,desc:"Transperce l'adversaire avec une corne acérée."},
  furyattack:{pp:20,name:'Furie',type:'normal',cat:'phys',power:45,accuracy:0.85,desc:"Attaque l'adversaire deux à cinq fois de suite."},
  waterfall:{pp:15,name:'Cascade',type:'eau',cat:'phys',power:65,accuracy:1,flinch:0.2,desc:"Charge comme une vague déferlante. Peut faire peur."},
  crabhammer:{pp:10,name:'Pince-Masse',type:'eau',cat:'phys',power:90,accuracy:0.85,desc:"Frappe avec de puissantes pinces de crabe."},
  twineedle:{pp:20,name:'Double-Dard',type:'insecte',cat:'phys',power:50,accuracy:1,secondaryStatus:{status:'poison',chance:0.2},desc:"Pique deux fois de suite. Peut empoisonner."},
  sing:{pp:15,name:'Berceuse',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.55,effect:{status:'sommeil'},desc:"Une mélodie apaisante qui endort l'adversaire."},
  doubleslap:{pp:10,name:'Torgnoles',type:'normal',cat:'phys',power:45,accuracy:0.85,desc:"Gifle l'adversaire deux à cinq fois de suite."},
  barrier:{pp:20,name:'Bouclier',type:'psy',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:2}]},desc:"Érige un mur psychique qui booste fortement la Défense."},
  meditate:{pp:40,name:'Yoga',type:'psy',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'atk',stages:1}]},desc:"Se concentre profondément pour booster son Attaque."},
  raindance:{pp:5,name:'Danse Pluie',type:'eau',cat:'status',power:0,target:'self',effect:{weather:'pluie'},desc:"Invoque une forte pluie pendant 5 tours."},
  sunnyday:{pp:5,name:'Zénith',type:'feu',cat:'status',power:0,target:'self',effect:{weather:'soleil'},desc:"Invoque un fort ensoleillement pendant 5 tours."},
  sandstorm:{pp:10,name:'Tempête de Sable',type:'roche',cat:'status',power:0,target:'self',effect:{weather:'sable'},desc:"Déclenche une tempête de sable pendant 5 tours."},
  hail:{pp:10,name:'Grêle',type:'glace',cat:'status',power:0,target:'self',effect:{weather:'grele'},desc:"Fait tomber une grêle glaciale pendant 5 tours."},
  absorb:{pp:25,name:'Vol-Vie',type:'plante',cat:'spec',power:35,accuracy:1,drain:0.5,desc:"Aspire l'énergie de l'adversaire pour se soigner."},

  growl:{pp:40,name:'Rugissement',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'atk',stages:-1}]},desc:"Un grondement mignon qui baisse l'Attaque adverse."},
  leer:{pp:30,name:"Groz'Yeux",type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'def',stages:-1}]},desc:"Un regard noir qui baisse la Défense adverse."},
  swordsdance:{pp:20,name:'Danse-Lames',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'atk',stages:2}]},desc:"Une danse endiablée qui booste fortement l'Attaque."},
  agility:{pp:30,name:'Agilité',type:'psy',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'spe',stages:2}]},desc:"Détend le corps pour booster fortement la Vitesse."},
  harden:{pp:30,name:'Harden',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:1}]},desc:"Raidit tout le corps pour booster la Défense."},
  amnesia:{pp:20,name:'Amnésie',type:'psy',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'spd',stages:2}]},desc:"Vide l'esprit pour booster fortement la Défense Spéciale."},
  toxic:{pp:10,name:'Toxik',type:'poison',cat:'status',power:0,target:'foe',accuracy:0.9,effect:{status:'poison'},desc:"Empoisonne gravement l'adversaire."},
  thunderwave:{pp:20,name:'Cage-Éclair',type:'electrik',cat:'status',power:0,target:'foe',accuracy:0.9,effect:{status:'paralysie'},desc:"Une faible décharge qui paralyse l'adversaire."},
  sleeppowder:{pp:15,name:'Poudre Dodo',type:'plante',cat:'status',power:0,target:'foe',accuracy:0.75,effect:{status:'sommeil'},desc:"Une poudre soporifique qui endort l'adversaire."},
  confuseray:{pp:10,name:'Onde Folie',type:'fantome',cat:'status',power:0,target:'foe',accuracy:1.0,effect:{status:'confusion'},desc:"Une lumière sinistre qui rend l'adversaire confus."},
  recover:{pp:10,name:'Soin',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Régénère la moitié de ses PV maximum."},
  strength:{pp:15,name:'Force',type:'normal',cat:'phys',power:80,accuracy:1,desc:"Pousse l'adversaire de toutes ses forces."},
  dragonrage:{pp:10,name:'Draco-Rage',type:'dragon',cat:'spec',power:0,accuracy:1,fixedDamage:40,desc:"Une attaque mystérieuse qui infligera toujours 40 dégâts."},

  /* ---- BLOC 1 : capacités manquantes (indices Pokédex 1-58) ---- */
  pound:{pp:35,name:"Écras'Face",type:'normal',cat:'phys',power:40,accuracy:1,desc:"Frappe la cible avec des pattes ou une longue queue."},
  cometpunch:{pp:15,name:'Poing Comète',type:'normal',cat:'phys',power:40,accuracy:0.85,desc:"Assène une volée de coups de poing rapides."},
  megapunch:{pp:20,name:'Ultimapoing',type:'normal',cat:'phys',power:75,accuracy:0.85,desc:"Un coup de poing d'une force phénoménale."},
  payday:{pp:20,name:'Jackpot',type:'normal',cat:'phys',power:40,accuracy:1,desc:"Lance des pièces qui blessent la cible."},
  visegrip:{pp:30,name:'Force Poigne',type:'normal',cat:'phys',power:55,accuracy:1,desc:"Saisit et écrase la cible dans une poigne puissante."},
  guillotine:{pp:5,name:'Guillotine',type:'normal',cat:'phys',power:0,ohko:true,accuracy:0.3,desc:"De redoutables pinces mettent K.O. la cible d'un coup si l'attaque touche."},
  razorwind:{pp:10,name:'Coupe-Vent',type:'normal',cat:'spec',power:60,accuracy:1,charge:true,chargeMsg:'prépare une tornade tranchante',desc:"Prépare une tornade puis tranche la cible à distance au tour suivant."},
  cut:{pp:30,name:'Coupe',type:'normal',cat:'phys',power:45,accuracy:0.95,desc:"Tranche la cible avec des griffes ou une faux."},
  whirlwind:{pp:20,name:'Cyclone',type:'normal',cat:'status',power:0,target:'foe',accuracy:1.0,effect:{forceSwitch:true},desc:"Une bourrasque qui force l'adversaire à quitter le combat."},
  fly:{pp:15,name:'Vol',type:'vol',cat:'phys',power:70,accuracy:0.95,charge:true,semiInvuln:'fly',chargeMsg:"prend son envol vers le ciel",desc:"Prend son envol (esquive les attaques, sauf Tornade/Ouragan/Fatal-Foudre/Stratopercut) puis fond sur la cible au tour suivant."},
  bind:{pp:20,name:'Étreinte',type:'normal',cat:'phys',power:40,accuracy:0.85,desc:"Enserre la cible dans une étreinte puissante."},
  slam:{pp:20,name:'Souplesse',type:'normal',cat:'phys',power:70,accuracy:0.75,desc:"Projette violemment la cible avec une longue queue ou des lianes."},
  megakick:{pp:5,name:'Ultimawashi',type:'normal',cat:'phys',power:90,accuracy:0.75,desc:"Un coup de pied d'une puissance colossale."},
  jumpkick:{pp:25,name:'Pied Sauté',type:'combat',cat:'phys',power:70,recoil:0.25,accuracy:0.95,desc:"Un puissant coup de pied sauté ; un échec blesserait l'attaquant."},
  rollingkick:{pp:15,name:'Mawashi Geri',type:'combat',cat:'phys',power:60,accuracy:0.85,desc:"Un coup de pied circulaire éclair."},
  sandattack:{pp:15,name:'Jet de Sable',type:'sol',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'acc',stages:-1}]},desc:"Projette du sable au visage de la cible pour réduire sa précision."},
  horndrill:{pp:5,name:"Empal'Korne",type:'normal',cat:'phys',power:0,ohko:true,accuracy:0.3,desc:"Une corne en vrille perfore la cible, la mettant K.O. d'un coup si l'attaque touche."},
  wrap:{pp:20,name:'Ligotage',type:'normal',cat:'phys',power:35,accuracy:0.85,desc:"Ligote la cible avec une longue liane ou un corps serpentin."},
  takedown:{pp:20,name:'Bélier',type:'normal',cat:'phys',power:65,accuracy:0.85,recoil:0.25,desc:"Une charge frontale ; l'attaquant subit aussi un peu de dégâts."},
  thrash:{pp:20,name:'Mania',type:'normal',cat:'phys',power:65,accuracy:1,desc:"Se déchaîne violemment sur la cible avec une force brute."},
  tailwhip:{pp:30,name:'Mimi-Queue',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'def',stages:-1}]},desc:"Balance sa queue pour attirer l'attention et baisser la Défense adverse."},
  supersonic:{pp:20,name:'Ultrason',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.55,effect:{status:'confusion'},desc:"Émet des ultrasons étranges qui rendent la cible confuse."},
  sonicboom:{pp:20,name:'Sonic Boom',type:'normal',cat:'spec',power:0,fixedDamage:20,accuracy:0.9,desc:"Une onde de choc qui inflige toujours 20 dégâts."},
  disable:{pp:20,name:'Entrave',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.8,effect:{disable:true},desc:"Empêche la cible d'utiliser sa dernière capacité pendant 4 tours."},
  mist:{pp:30,name:'Brume',type:'glace',cat:'status',power:0,target:'self',effect:{mist:true},desc:"Enveloppe l'équipe d'une brume qui protège des baisses de statistiques pendant 5 tours."},

  /* ---- BLOC 2 : capacités manquantes (indices Pokédex 59-115) ---- */
  aurorabeam:{pp:20,name:'Onde Boréale',type:'glace',cat:'spec',power:55,accuracy:1,secondaryBoost:{stat:'atk',stages:-1,chance:0.1},desc:"Un rayon arc-en-ciel qui peut réduire l'Attaque de la cible."},
  lowkick:{pp:20,name:'Frappe Talon',type:'combat',cat:'phys',power:60,accuracy:1,desc:"Un coup de pied bas qui déséquilibre la cible."},
  counter:{pp:20,name:'Riposte',type:'combat',cat:'phys',power:0,accuracy:1,counter:true,desc:"Riposte en renvoyant le double des dégâts physiques subis ce tour."},
  seismictoss:{pp:20,name:'Frappe Atlas',type:'combat',cat:'phys',power:0,accuracy:1,fixedDamage:50,desc:"Une prise de catch qui inflige toujours 50 dégâts."},
  growth:{pp:20,name:'Croissance',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'spa',stages:1}]},desc:"Le corps grandit soudainement, boostant l'Attaque Spéciale."},
  poisonpowder:{pp:35,name:'Poudre Toxik',type:'poison',cat:'status',power:0,target:'foe',accuracy:0.75,effect:{status:'poison'},desc:"Disperse une poudre toxique qui empoisonne la cible."},
  stunspore:{pp:30,name:'Para-Spore',type:'plante',cat:'status',power:0,target:'foe',accuracy:0.75,effect:{status:'paralysie'},desc:"Disperse une poudre paralysante sur la cible."},
  petaldance:{pp:20,name:'Danse-Fleur',type:'plante',cat:'phys',power:65,accuracy:1,desc:"Se déchaîne au milieu d'une tempête de pétales."},
  stringshot:{pp:40,name:'Sécrétion',type:'insecte',cat:'status',power:0,accuracy:0.95,target:'foe',effect:{foeBoost:[{stat:'spe',stages:-1}]},desc:"Recouvre la cible d'un fil collant qui réduit sa Vitesse."},
  firespin:{pp:15,name:'Danseflamme',type:'feu',cat:'spec',power:40,accuracy:0.85,desc:"Emprisonne la cible dans un tourbillon de flammes."},
  fissure:{pp:5,name:'Lame du Vide',type:'sol',cat:'phys',power:0,ohko:true,accuracy:0.3,bypassInvuln:['dig'],desc:"Ouvre une crevasse qui engloutit la cible (même sous terre), la mettant K.O. d'un coup si l'attaque touche."},
  hypnosis:{pp:20,name:'Hypnose',type:'psy',cat:'status',power:0,target:'foe',accuracy:0.6,effect:{status:'sommeil'},desc:"Un regard hypnotique qui endort la cible."},
  rage:{pp:20,name:'Frénésie',type:'normal',cat:'phys',power:40,accuracy:1,desc:"Une charge rageuse et impulsive."},
  teleport:{pp:20,name:'Téléport',type:'psy',cat:'status',power:0,target:'self',effect:{selfSwitch:true},desc:"Se téléporte hors de portée pour laisser place à un autre Pokémon."},
  mimic:{pp:10,name:'Copie',type:'normal',cat:'status',power:0,target:'self',effect:{mimic:true},desc:"Copie la dernière capacité utilisée par l'adversaire pour le reste du combat."},
  screech:{pp:40,name:'Grincement',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.85,effect:{foeBoost:[{stat:'def',stages:-2}]},desc:"Un cri strident qui baisse fortement la Défense adverse."},
  doubleteam:{pp:15,name:'Reflet',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'eva',stages:1}]},desc:"Crée des copies illusoires qui augmentent l'Esquive."},
  minimize:{pp:20,name:'Lilliput',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'eva',stages:2}]},desc:"Se recroqueville pour augmenter fortement l'Esquive."},
  smokescreen:{pp:20,name:'Écran Fumée',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'acc',stages:-1}]},desc:"Répand un écran de fumée qui réduit la précision adverse."},
  withdraw:{pp:40,name:'Repli',type:'eau',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:1}]},desc:"Se rétracte dans sa carapace pour booster la Défense."},
  defensecurl:{pp:40,name:"Boul'Armure",type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:1}]},desc:"Se roule en boule pour cacher ses points faibles et booster la Défense."},
  lightscreen:{pp:30,name:'Mur Lumière',type:'psy',cat:'status',power:0,target:'self',effect:{lightScreen:true},desc:"Érige un mur qui réduit les dégâts des capacités Spéciales pendant 5 tours."},
  haze:{pp:30,name:'Brouillard',type:'glace',cat:'status',power:0,target:'self',effect:{haze:true},desc:"Un brouillard épais annule tous les changements de statistiques en cours."},
  reflect:{pp:20,name:'Protection',type:'psy',cat:'status',power:0,target:'self',effect:{reflect:true},desc:"Érige un mur qui réduit les dégâts des capacités Physiques pendant 5 tours."},

  /* ---- BLOC 3 : capacités manquantes (fin de la Gen 1, indices ~116-155) ---- */
  focusenergy:{pp:30,name:'Puissance',type:'normal',cat:'status',power:0,target:'self',effect:{critBoost:true},desc:"Se concentre intensément pour améliorer ses chances de coup critique."},
  bide:{pp:10,name:'Patience',type:'normal',cat:'phys',power:70,accuracy:1,desc:"Encaisse puis riposte avec une force redoublée."},
  metronome:{pp:10,name:'Métronome',type:'normal',cat:'status',power:0,target:'self',metronome:true,effect:{},desc:"Agite un doigt et invoque presque n'importe quelle capacité au hasard."},
  mirrormove:{pp:20,name:'Mimique',type:'vol',cat:'status',power:0,target:'self',mirrorMove:true,effect:{},desc:"Copie et utilise immédiatement la dernière capacité employée par l'adversaire."},
  selfdestruct:{pp:5,name:'Destruction',type:'normal',cat:'phys',power:130,accuracy:1,selfDestruct:true,desc:"Une explosion dévastatrice qui met K.O. son lanceur."},
  explosion:{pp:5,name:'Explosion',type:'normal',cat:'phys',power:170,accuracy:1,selfDestruct:true,desc:"Une explosion titanesque qui met K.O. son lanceur."},
  eggbomb:{pp:10,name:"Bomb'Œuf",type:'normal',cat:'phys',power:70,accuracy:0.75,desc:"Projette un œuf massif sur la cible."},
  smog:{pp:20,name:'Puredpois',type:'poison',cat:'spec',power:40,accuracy:0.7,secondaryStatus:{status:'poison',chance:0.4},desc:"Un nuage de gaz sale qui peut empoisonner la cible."},
  boneclub:{pp:20,name:"Massd'Os",type:'sol',cat:'phys',power:55,accuracy:0.85,flinch:0.1,desc:"Frappe avec un os solide. Peut faire peur."},
  clamp:{pp:15,name:'Coquille',type:'eau',cat:'phys',power:40,accuracy:0.85,desc:"Enferme la cible dans une coquille robuste."},
  skullbash:{pp:15,name:"Coud'Krâne",type:'normal',cat:'phys',power:80,accuracy:1,charge:true,chargeMsg:'rentre la tête dans sa carapace',desc:"Rentre la tête puis fonce avec une puissance colossale au tour suivant."},
  spikecannon:{pp:15,name:'Picanon',type:'normal',cat:'phys',power:50,accuracy:1,desc:"Tire une volée de pointes acérées sur la cible."},
  constrict:{pp:35,name:'Constriction',type:'normal',cat:'phys',power:35,accuracy:1,secondaryBoost:{stat:'spe',stages:-1,chance:0.1},desc:"Étouffe la cible avec de longs tentacules ou lianes."},
  kinesis:{pp:15,name:'Télékinésie',type:'psy',cat:'status',power:0,target:'foe',accuracy:0.8,effect:{foeBoost:[{stat:'acc',stages:-1}]},desc:"Tord une cuillère pour brouiller l'esprit de la cible et baisser sa précision."},
  softboiled:{pp:10,name:'E-Coque',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Sacrifie un peu de son propre corps pour récupérer la moitié de ses PV max."},
  glare:{pp:30,name:'Intimidation',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.75,effect:{status:'paralysie'},desc:"Un regard intimidant qui paralyse la cible."},
  dreameater:{pp:15,name:'Dévorêve',type:'psy',cat:'spec',power:65,accuracy:1,drain:0.5,sleepOnly:true,desc:"Dévore les rêves de la cible endormie et absorbe des PV. Échoue si la cible est éveillée."},
  poisongas:{pp:40,name:'Gaz Toxik',type:'poison',cat:'status',power:0,target:'foe',accuracy:0.55,effect:{status:'poison'},desc:"Asperge la cible d'un gaz toxique."},
  barrage:{pp:20,name:'Pilonnage',type:'normal',cat:'phys',power:45,accuracy:0.85,desc:"Bombarde la cible avec des sphères rondes."},
  lovelykiss:{pp:10,name:'Grobisou',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.75,effect:{status:'sommeil'},desc:"Un baiser irrésistible qui endort la cible."},
  skyattack:{pp:5,name:'Pique',type:'vol',cat:'phys',power:85,accuracy:0.9,desc:"Fond sur la cible depuis les cieux avec une force phénoménale."},
  transform:{pp:10,name:'Morphing',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{transform:true},desc:"Se transforme en copie exacte de l'adversaire, empruntant son apparence et ses capacités."},
  dizzypunch:{pp:10,name:'Uppercut',type:'normal',cat:'phys',power:60,accuracy:1,secondaryStatus:{status:'confusion',chance:0.2},desc:"Un coup de poing rotatif qui peut rendre confus."},
  spore:{pp:15,name:'Spore',type:'plante',cat:'status',power:0,accuracy:1,target:'foe',effect:{status:'sommeil'},desc:"Libère un nuage de spores qui endort infailliblement la cible."},
  flash:{pp:20,name:'Flash',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'acc',stages:-1}]},desc:"Un éclair de lumière aveuglant qui baisse la précision adverse."},
  psywave:{pp:15,name:'Vague Psy',type:'psy',cat:'spec',power:0,accuracy:1,psywave:true,desc:"Inflige des dégâts d'intensité aléatoire et imprévisible."},
  splash:{pp:40,name:'Trempette',type:'normal',cat:'status',power:0,target:'self',effect:{noop:true},desc:"Le lanceur fait juste des éclaboussures... ça ne sert absolument à rien."},
  acidarmor:{pp:40,name:'Carapace Armure',type:'poison',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:2}]},desc:"Liquéfie son corps pour booster fortement la Défense."},
  furyswipes:{pp:15,name:'Griffes Furie',type:'normal',cat:'phys',power:45,accuracy:0.8,desc:"Griffe la cible à répétition, rapidement et sauvagement."},
  rest:{pp:10,name:'Repos',type:'psy',cat:'status',power:0,target:'self',effect:{rest:true},desc:"S'endort profondément pendant 2 tours pour récupérer tous ses PV et soigner ses altérations d'état."},
  sharpen:{pp:30,name:'Affûtage',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'atk',stages:1}]},desc:"Durcit son corps anguleux pour booster son Attaque."},
  conversion:{pp:30,name:'Conversion',type:'normal',cat:'status',power:0,target:'self',effect:{},desc:"Change de type pour adopter celui de sa première capacité."},
  triattack:{pp:10,name:'Triplattaque',type:'normal',cat:'spec',power:65,accuracy:1,triStatus:true,desc:"Tire trois faisceaux simultanés qui peuvent brûler, geler ou paralyser la cible."},
  superfang:{pp:10,name:'Croc Fatal',type:'normal',cat:'phys',power:0,halfHp:true,accuracy:0.9,desc:"Mord violemment pour réduire de moitié les PV actuels de la cible."},

  /* ---- BLOC 4 : vraies capacités de Génération 2 ---- */
  sketch:{pp:1,name:'Gribouille',type:'normal',cat:'status',power:0,target:'self',effect:{mimic:true},desc:"Copie durablement la dernière capacité utilisée par l'adversaire."},
  triplekick:{pp:10,name:'Triple Pied',type:'combat',cat:'phys',power:40,accuracy:0.9,desc:"Trois coups de pied enchaînés à la suite."},
  thief:{pp:10,name:'Implore',type:'tenebres',cat:'phys',power:40,accuracy:1,desc:"Une attaque sournoise qui déroberait normalement l'objet tenu de la cible."},
  spiderweb:{pp:10,name:'Toile',type:'insecte',cat:'status',power:0,accuracy:1,target:'foe',effect:{trap:true},desc:"Emprisonne la cible dans une toile qui l'empêche de fuir."},
  mindreader:{pp:5,name:'Lire-Esprit',type:'normal',cat:'status',power:0,target:'self',effect:{lockOn:true},desc:"Verrouille la cible : la prochaine capacité ne pourra pas rater."},
  nightmare:{pp:15,name:'Cauchemar',type:'fantome',cat:'spec',power:30,accuracy:1,sleepOnly:true,desc:"Plonge la cible endormie dans un cauchemar douloureux."},
  flamewheel:{pp:25,name:'Roue de Feu',type:'feu',cat:'phys',power:55,accuracy:1,secondaryStatus:{status:'brulure',chance:0.1},desc:"Une roue de flammes qui peut brûler la cible."},
  snore:{pp:15,name:'Ronflement',type:'normal',cat:'spec',power:45,accuracy:1,selfSleepOnly:true,flinch:0.3,desc:"Une attaque utilisable uniquement en dormant. Peut faire peur."},
  curse:{pp:10,name:'Malédiction',type:'fantome',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'atk',stages:1},{stat:'def',stages:1},{stat:'spe',stages:-1}]},desc:"Un rituel qui booste l'Attaque et la Défense au prix de la Vitesse."},
  flail:{pp:15,name:'Ruade',type:'normal',cat:'phys',power:20,accuracy:1,lowHpBoost:true,desc:"Une ruade désespérée, d'autant plus puissante que les PV sont bas."},
  conversion2:{pp:30,name:'Conversion 2',type:'normal',cat:'status',power:0,target:'self',effect:{},desc:"Change de type pour résister au dernier type qui a touché le lanceur."},
  aeroblast:{pp:5,name:'Aéroblast',type:'vol',cat:'spec',power:85,accuracy:0.95,desc:"Un puissant tourbillon d'air projeté sur la cible."},
  cottonspore:{pp:40,name:'Spore Coton',type:'plante',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'spe',stages:-2}]},desc:"Colle des fibres cotonneuses qui réduisent fortement la Vitesse adverse."},
  reversal:{pp:15,name:'Renversement',type:'combat',cat:'phys',power:20,accuracy:1,lowHpBoost:true,desc:"Une contre-attaque désespérée, d'autant plus puissante que les PV sont bas."},
  spite:{pp:10,name:'Dépit',type:'fantome',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Réduit rageusement les PP de la dernière capacité utilisée par la cible."},
  powdersnow:{pp:25,name:'Poudreuse',type:'glace',cat:'spec',power:40,accuracy:1,secondaryStatus:{status:'gel',chance:0.1},desc:"Une bourrasque de neige poudreuse qui peut geler la cible."},
  protect:{pp:10,name:'Abri',type:'normal',cat:'status',power:0,target:'self',priority:4,effect:{protect:true},desc:"Protège totalement des attaques ce tour-ci."},
  machpunch:{pp:30,name:'Mach Punch',type:'combat',cat:'phys',power:40,accuracy:1,priority:1,desc:"Un coup de poing fulgurant qui touche en premier."},
  scaryface:{pp:10,name:'Grimace',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'spe',stages:-2}]},desc:"Une grimace terrifiante qui baisse fortement la Vitesse adverse."},
  sweetkiss:{pp:10,name:'Doux Baiser',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.75,effect:{status:'confusion'},desc:"Un baiser espiègle qui rend la cible confuse."},
  bellydrum:{pp:10,name:'Tambour',type:'normal',cat:'status',power:0,target:'self',effect:{bellyDrum:true},desc:"Sacrifie la moitié de ses PV max pour maximiser son Attaque d'un coup."},
  mudslap:{pp:10,name:'Coud\u2019Boue',type:'sol',cat:'spec',power:20,accuracy:1,secondaryBoost:{stat:'acc',stages:-1,chance:1.0},desc:"Projette de la boue au visage de la cible et réduit sa précision."},
  octazooka:{pp:10,name:'Octo-Canon',type:'eau',cat:'spec',power:65,accuracy:0.85,secondaryBoost:{stat:'acc',stages:-1,chance:0.5},desc:"Tire un jet d'encre qui peut réduire la précision de la cible."},
  spikes:{pp:20,name:'Pointes',type:'sol',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Dispose des pointes acérées sur le terrain adverse."},
  zapcannon:{pp:5,name:'Élecanon',type:'electrik',cat:'spec',power:100,accuracy:0.5,secondaryStatus:{status:'paralysie',chance:1.0},desc:"Un tir surpuissant qui paralyse systématiquement s'il touche."},
  foresight:{pp:40,name:'Clairvoyance',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Permet normalement de toucher les Pokémon Spectre et d'ignorer les hausses d'Esquive."},
  destinybond:{pp:5,name:'Lien du Destin',type:'fantome',cat:'status',power:0,target:'self',effect:{},desc:"Si le lanceur est mis K.O. ce tour, l'adversaire responsable devrait subir le même sort."},
  perishsong:{pp:5,name:'Requiem',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{perishSong:true},desc:"Tous les Pokémon sur le terrain seront K.O. dans 3 tours."},
  detect:{pp:5,name:'Détection',type:'combat',cat:'status',power:0,target:'self',priority:4,effect:{protect:true},desc:"Anticipe et évite totalement les attaques ce tour-ci."},
  bonerush:{pp:10,name:'Os Rush',type:'sol',cat:'phys',power:25,accuracy:0.9,desc:"Frappe la cible à répétition avec un os solide."},
  lockon:{pp:5,name:'Verrouillage',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{lockOn:true},desc:"Verrouille fermement la cible : la prochaine capacité ne pourra pas rater."},
  outrage:{pp:15,name:'Dracocolère',type:'dragon',cat:'phys',power:75,accuracy:1,desc:"Se déchaîne violemment dans une rage draconique incontrôlable."},
  endure:{pp:10,name:'Ténacité',type:'normal',cat:'status',power:0,target:'self',priority:4,effect:{endure:true},desc:"Permet de survivre à 1 PV face à n'importe quelle attaque ce tour-ci."},
  charm:{pp:20,name:'Charme',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'atk',stages:-2}]},desc:"Un regard adorable qui baisse fortement l'Attaque adverse."},
  rollout:{pp:20,name:'Roulade',type:'roche',cat:'phys',power:30,accuracy:0.9,desc:"Une charge roulante qui gagne en puissance à chaque utilisation."},
  falseswipe:{pp:40,name:'Faux-Chage',type:'normal',cat:'phys',power:40,accuracy:1,desc:"Une attaque tout en retenue qui laisse toujours au moins 1 PV à la cible."},
  swagger:{pp:15,name:'Vantardise',type:'normal',cat:'status',power:0,target:'foe',accuracy:0.85,effect:{foeBoost:[{stat:'atk',stages:2}],status:'confusion'},desc:"Provoque la cible pour booster son Attaque tout en la rendant confuse."},
  milkdrink:{pp:10,name:'Lait Soin',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Un lait nourrissant qui restaure la moitié des PV max."},
  spark:{pp:20,name:'Étincelle',type:'electrik',cat:'phys',power:65,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.3},desc:"Une charge électrifiée qui peut paralyser la cible."},
  furycutter:{pp:20,name:'Taillade',type:'insecte',cat:'phys',power:20,accuracy:0.95,desc:"Une lame tranchante dont la puissance augmente à chaque coup consécutif."},
  meanlook:{pp:5,name:'Regard Noir',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{trap:true},desc:"Un regard menaçant qui empêche la cible de fuir ou de switcher."},
  attract:{pp:15,name:'Attraction',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Rend la cible amoureuse, ce qui peut l'empêcher d'attaquer."},
  sleeptalk:{pp:10,name:'Blabla Dodo',type:'normal',cat:'status',power:0,target:'self',selfSleepOnly:true,effect:{},desc:"Utilise une capacité au hasard tout en dormant profondément."},
  healbell:{pp:5,name:'Chant Guérison',type:'normal',cat:'status',power:0,target:'self',effect:{cureStatus:true},desc:"Une douce mélodie qui guérit toutes les altérations de statut de l'équipe."},
  return:{pp:20,name:'Retour',type:'normal',cat:'phys',power:70,accuracy:1,desc:"Une attaque dont la puissance grandit avec l'affection envers le dresseur."},
  present:{pp:15,name:'Cadeau',type:'normal',cat:'phys',power:0,accuracy:0.9,present:true,desc:"Offre un cadeau surprise : parfois un soin, parfois une explosion de dégâts."},
  frustration:{pp:20,name:'Frustration',type:'normal',cat:'phys',power:70,accuracy:1,desc:"Une attaque dont la puissance grandit avec le mécontentement envers le dresseur."},
  safeguard:{pp:25,name:'Rune Protect',type:'normal',cat:'status',power:0,target:'self',effect:{safeguard:true},desc:"Protège l'équipe de toute altération de statut pendant 5 tours."},
  painsplit:{pp:20,name:'Partage Douleur',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{painSplit:true},desc:"Fait la moyenne des PV actuels du lanceur et de la cible."},
  sacredfire:{pp:5,name:'Feu Sacré',type:'feu',cat:'phys',power:90,accuracy:0.95,secondaryStatus:{status:'brulure',chance:0.5},desc:"Un feu sacré et purificateur qui peut sévèrement brûler la cible."},
  magnitude:{pp:30,name:'Ampleur',type:'sol',cat:'phys',power:0,accuracy:1,variablePower:true,bypassInvuln:['dig'],desc:"Un séisme d'intensité totalement imprévisible. Touche même les cibles sous terre."},
  dynamicpunch:{pp:5,name:'Dynamopoing',type:'combat',cat:'phys',power:100,accuracy:0.5,secondaryStatus:{status:'confusion',chance:1.0},desc:"Un coup de poing surpuissant qui rend systématiquement confus s'il touche."},
  batonpass:{pp:40,name:'Relais',type:'normal',cat:'status',power:0,target:'self',effect:{selfSwitch:true,batonPass:true},desc:"Cède sa place à un autre Pokémon en lui transmettant ses changements de statistiques."},
  encore:{pp:5,name:'Encore',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Force normalement la cible à répéter sa dernière capacité."},
  pursuit:{pp:20,name:'Poursuite',type:'tenebres',cat:'phys',power:40,accuracy:1,desc:"Frappe la cible avec une force redoublée si elle s'apprête à fuir."},
  rapidspin:{pp:40,name:'Tour Rapide',type:'normal',cat:'phys',power:20,accuracy:1,desc:"Une attaque tournoyante qui élimine normalement les pièges au sol."},
  sweetscent:{pp:20,name:'Doux Parfum',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'eva',stages:-2}]},desc:"Un parfum enivrant qui baisse fortement l'Esquive adverse."},
  irontail:{pp:15,name:'Queue de Fer',type:'acier',cat:'phys',power:75,accuracy:0.75,secondaryBoost:{stat:'def',stages:-1,chance:0.3},desc:"Un coup de queue métallique qui peut réduire la Défense adverse."},
  metalclaw:{pp:35,name:'Griffe Acier',type:'acier',cat:'phys',power:45,accuracy:0.95,secondarySelfBoost:{stat:'atk',stages:1,chance:0.1},desc:"Des griffes d'acier qui peuvent booster l'Attaque du lanceur."},
  vitalthrow:{pp:10,name:'Frappe Atout',type:'combat',cat:'phys',power:60,accuracy:1.0,desc:"Une prise qui riposte toujours après l'adversaire, mais ne rate jamais."},
  morningsun:{pp:5,name:'Salut Soleil',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Absorbe la lumière du soleil pour récupérer la moitié de ses PV max."},
  synthesis:{pp:5,name:'Synthèse',type:'plante',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Utilise l'énergie ambiante pour récupérer la moitié de ses PV max."},
  moonlight:{pp:5,name:'Clair de Lune',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Absorbe la lumière de la lune pour récupérer la moitié de ses PV max."},
  hiddenpower:{pp:15,name:'Puissance Cachée',type:'normal',cat:'spec',power:60,accuracy:1,desc:"Une capacité unique dont le type varie normalement selon chaque Pokémon."},
  twister:{pp:20,name:'Ouragan',type:'dragon',cat:'spec',power:40,accuracy:1,flinch:0.2,bypassInvuln:['fly'],desc:"Un tourbillon tranchant qui peut faire peur à la cible. Touche même les cibles en plein vol."},
  mirrorcoat:{pp:20,name:'Voile Miroir',type:'psy',cat:'spec',power:0,accuracy:1,mirrorCoat:true,desc:"Renvoie le double des dégâts Spéciaux subis ce tour."},
  psychup:{pp:10,name:'Boost',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{psychUp:true},desc:"Copie tous les changements de statistiques actuels de la cible."},
  extremespeed:{pp:5,name:'Vitesse Extrême',type:'normal',cat:'phys',power:70,accuracy:1,priority:2,desc:"Une charge d'une rapidité fulgurante qui touche presque toujours en premier."},
  ancientpower:{pp:5,name:'Puissance Antique',type:'roche',cat:'spec',power:55,accuracy:1,secondarySelfBoost:{stat:'atk',stages:1,chance:0.1},desc:"Une énergie ancestrale qui peut booster les capacités du lanceur."},
  futuresight:{pp:10,name:'Prescience',type:'psy',cat:'spec',power:80,accuracy:0.9,futureSight:true,desc:"Prédit l'avenir : la cible est frappée par une force psychique 2 tours plus tard."},
  rocksmash:{pp:15,name:'Éclate-Roc',type:'combat',cat:'phys',power:40,accuracy:1,secondaryBoost:{stat:'def',stages:-1,chance:0.5},desc:"Un coup puissant qui peut réduire la Défense de la cible."},
  whirlpool:{pp:15,name:'Siphon',type:'eau',cat:'spec',power:35,accuracy:0.85,bypassInvuln:['dive'],desc:"Emprisonne la cible dans un tourbillon aquatique. Touche même les cibles qui plongent."},
  beatup:{pp:10,name:'Baston',type:'tenebres',cat:'phys',power:55,accuracy:1,desc:"Toute l'équipe se relaie pour frapper la cible tour à tour."},

  /* ---- BLOC 3 (Gen 4) : nouvelles capacités ---- */
  aurasphere:{pp:20,name:'Aurasphère',type:'combat',cat:'spec',power:80,accuracy:1.0,desc:"Une onde d'énergie pure tirée du plus profond de soi. Ne rate jamais."},
  closecombat:{pp:5,name:'Close Combat',type:'combat',cat:'phys',power:120,accuracy:1,selfBoost:[{stat:'atk',stages:-1},{stat:'def',stages:-1}],desc:"Attaque de plein fouet sans se soucier de sa garde, au prix de ses défenses."},
  focusblast:{pp:5,name:'Exploforce',type:'combat',cat:'spec',power:120,accuracy:0.7,secondaryBoost:{stat:'spd',stages:-1,chance:0.1},desc:"Concentre son énergie en une sphère dévastatrice. Peut réduire la Défense Spéciale."},
  dracometeor:{pp:5,name:'Draco-Météore',type:'dragon',cat:'spec',power:130,accuracy:0.9,selfBoost:[{stat:'spa',stages:-2}],desc:"Convoque une pluie de météores draconiques qui épuise le lanceur."},
  dragonpulse:{pp:10,name:'Dracochoc',type:'dragon',cat:'spec',power:85,accuracy:1,desc:"Libère une onde de choc depuis sa mâchoire grande ouverte."},
  uturn:{pp:20,name:'Demi-Tour',type:'insecte',cat:'phys',power:70,accuracy:1,effect:{selfSwitch:true},desc:"Frappe puis rebrousse chemin à toute vitesse, cédant sa place à un autre Pokémon."},
  stealthrock:{pp:20,name:'Piège de Roc',type:'roche',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Dispose des pierres pointues flottantes autour du camp adverse."},

  /* ---- BLOC 2 (Gen 3) : nouvelles capacités ---- */
  stridoson:{pp:40,name:'Strido-Son',type:'acier',cat:'status',power:0,target:'foe',accuracy:0.85,effect:{foeBoost:[{stat:'spd',stages:-2}]},desc:"Un cri métallique perçant qui baisse fortement la Défense Spéciale adverse."},
  meteormash:{pp:10,name:'Poing Météor',type:'acier',cat:'phys',power:100,accuracy:0.85,secondarySelfBoost:{stat:'atk',stages:1,chance:0.2},desc:"Un poing d'acier propulsé telle une comète. Peut booster l'Attaque."},
  doomdesire:{pp:5,name:'Carnareket',type:'acier',cat:'spec',power:130,accuracy:0.85,desc:"Libère une énergie destructrice d'une puissance colossale."},
  bulkup:{pp:20,name:'Gonflette',type:'combat',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'atk',stages:1},{stat:'def',stages:1}]},desc:"Gonfle ses muscles pour booster l'Attaque et la Défense."},
  armthrust:{pp:15,name:'Cogne',type:'combat',cat:'phys',power:40,accuracy:1,desc:"Une série de coups de bras rapides et répétés."},
  revenge:{pp:10,name:'Vendetta',type:'combat',cat:'phys',power:60,accuracy:1,desc:"Une contre-attaque redoutable envers qui vient de frapper."},
  skyuppercut:{pp:15,name:'Stratopercut',type:'combat',cat:'phys',power:85,accuracy:0.9,bypassInvuln:['fly'],desc:"Un uppercut monumental qui atteint même les cibles en plein vol."},
  superpower:{pp:5,name:'Surpuissance',type:'combat',cat:'phys',power:120,accuracy:1,selfBoost:[{stat:'atk',stages:-1},{stat:'def',stages:-1}],desc:"Une attaque d'une force colossale qui affaiblit un peu le lanceur."},
  focuspunch:{pp:20,name:'Mitra-Poing',type:'combat',cat:'phys',power:150,accuracy:1,desc:"Un coup de poing concentré d'une puissance dévastatrice."},
  dragondance:{pp:20,name:'Danse Draco',type:'dragon',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'atk',stages:1},{stat:'spe',stages:1}]},desc:"Une danse rituelle qui booste l'Attaque et la Vitesse."},
  watersport:{pp:15,name:'Tourniquet',type:'eau',cat:'status',power:0,target:'self',effect:{},desc:"S'asperge d'eau pour affaiblir les attaques Feu subies."},
  waterpulse:{pp:20,name:'Vibraqua',type:'eau',cat:'spec',power:60,accuracy:1,secondaryStatus:{status:'confusion',chance:0.2},desc:"Une onde aquatique qui peut rendre la cible confuse."},
  dive:{pp:10,name:'Plongée',type:'eau',cat:'spec',power:80,accuracy:1,charge:true,semiInvuln:'dive',chargeMsg:"plonge sous l'eau",desc:"Plonge sous l'eau (esquive les attaques, sauf Surf/Siphon) avant de refaire surface sur la cible au tour suivant."},
  muddywater:{pp:10,name:'Ocroupi',type:'eau',cat:'spec',power:95,accuracy:0.85,secondaryBoost:{stat:'acc',stages:-1,chance:0.3},desc:"Une vague boueuse qui peut réduire la précision adverse."},
  hydrocannon:{pp:5,name:'Hydroblast',type:'eau',cat:'spec',power:150,accuracy:0.9,desc:"Un canon d'eau d'une puissance phénoménale."},
  charge:{pp:20,name:'Chargeur',type:'electrik',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'spd',stages:1}]},desc:"Accumule de l'énergie électrique pour la prochaine attaque."},
  shockwave:{pp:20,name:'Onde de Choc',type:'electrik',cat:'spec',power:60,accuracy:1.0,desc:"Une décharge qui ne rate presque jamais sa cible."},
  volttackle:{pp:15,name:'Électacle',type:'electrik',cat:'phys',power:120,accuracy:1,recoil:0.33,desc:"Une charge électrifiée d'une puissance immense, mais douloureuse pour le lanceur."},
  willowisp:{pp:15,name:'Feu Follet',type:'feu',cat:'status',power:0,target:'foe',accuracy:0.75,effect:{status:'brulure'},desc:"Une flamme sinistre qui brûle la cible."},
  blazekick:{pp:10,name:'Pied Brûleur',type:'feu',cat:'phys',power:85,accuracy:0.9,secondaryStatus:{status:'brulure',chance:0.1},desc:"Un coup de pied enflammé qui peut brûler la cible."},
  heatwave:{pp:10,name:'Canicule',type:'feu',cat:'spec',power:100,accuracy:0.9,secondaryStatus:{status:'brulure',chance:0.1},desc:"Une vague de chaleur torride qui peut brûler la cible."},
  overheat:{pp:5,name:'Surchauffe',type:'feu',cat:'spec',power:140,accuracy:0.9,selfBoost:[{stat:'spa',stages:-2}],desc:"Une explosion de chaleur intense qui affaiblit l'Attaque Spéciale du lanceur."},
  blastburn:{pp:5,name:'Rafale Feu',type:'feu',cat:'spec',power:150,accuracy:0.9,desc:"Un torrent de flammes d'une puissance dévastatrice."},
  eruption:{pp:5,name:'Éruption',type:'feu',cat:'spec',power:150,accuracy:1,highHpBoost:true,desc:"Une explosion de lave, d'autant plus puissante que le lanceur est en pleine forme."},
  sheercold:{pp:5,name:'Glaciation',type:'glace',cat:'spec',power:0,ohko:true,accuracy:0.3,desc:"Un froid glacial qui met K.O. la cible d'un coup si l'attaque touche."},
  iciclespear:{pp:30,name:'Stalagtite',type:'glace',cat:'phys',power:45,accuracy:1,desc:"Mitraille la cible de glaçons acérés à répétition."},
  iceball:{pp:20,name:'Ball\u2019Glace',type:'glace',cat:'phys',power:35,accuracy:0.9,desc:"Une boule de glace roulante qui gagne en puissance à chaque tour."},
  tailglow:{pp:20,name:'Lumiqueue',type:'insecte',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'spa',stages:3}]},desc:"Une lueur hypnotique qui booste fortement l'Attaque Spéciale."},
  silverwind:{pp:5,name:'Vent Argenté',type:'insecte',cat:'spec',power:60,accuracy:1,secondarySelfBoost:{stat:'atk',stages:1,chance:0.1},desc:"Une poussière d'écailles scintillantes qui peut booster le lanceur."},
  signalbeam:{pp:15,name:'Rayon Signal',type:'insecte',cat:'spec',power:75,accuracy:1,secondaryStatus:{status:'confusion',chance:0.1},desc:"Un rayon étrange qui peut rendre la cible confuse."},
  swallow:{pp:10,name:'Avale',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Absorbe l'énergie accumulée pour restaurer ses PV."},
  stockpile:{pp:20,name:'Stockage',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:1},{stat:'spd',stages:1}]},desc:"Accumule de l'énergie défensive."},
  howl:{pp:40,name:'Grondement',type:'normal',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'atk',stages:1}]},desc:"Un hurlement qui booste l'Attaque du lanceur."},
  natureforce:{pp:20,name:'Force-Nature',type:'normal',cat:'spec',power:80,accuracy:1,desc:"Une capacité mystérieuse qui change de nature selon le terrain."},
  spitup:{pp:10,name:'Relâche',type:'normal',cat:'phys',power:75,accuracy:1,desc:"Libère l'énergie stockée sous forme d'attaque puissante."},
  wish:{pp:10,name:'Voeu',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Fait un voeu qui restaure les PV du lanceur."},
  assist:{pp:20,name:'Assistance',type:'normal',cat:'status',power:0,target:'self',metronome:true,effect:{},desc:"Invoque au hasard une capacité connue par l'équipe."},
  recycle:{pp:10,name:'Recyclage',type:'normal',cat:'status',power:0,target:'self',effect:{recycle:true},desc:"Récupère un objet tenu déjà consommé."},
  yawn:{pp:10,name:'Bâillement',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{status:'sommeil'},desc:"Donne sérieusement envie de dormir à la cible."},
  refresh:{pp:20,name:'Régénération',type:'normal',cat:'status',power:0,target:'self',effect:{cureStatus:true},desc:"Soigne le lanceur de tout problème de statut."},
  camouflage:{pp:20,name:'Camouflage',type:'normal',cat:'status',power:0,target:'self',effect:{},desc:"Change de type en fonction du terrain environnant."},
  teeterdance:{pp:20,name:'Danse-Folle',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{dualConfuse:true},desc:"Une danse étourdissante qui rend tout le monde confus."},
  slackoff:{pp:10,name:'Paresse',type:'normal',cat:'status',power:0,target:'self',effect:{heal:0.5},desc:"Se relâche complètement pour restaurer la moitié de ses PV max."},
  odorsleuth:{pp:40,name:'Flair',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Permet de toucher un Pokémon Spectre avec des capacités Normal ou Combat."},
  tickle:{pp:20,name:'Chatouille',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{foeBoost:[{stat:'atk',stages:-1},{stat:'def',stages:-1}]},desc:"Des chatouilles qui baissent l'Attaque et la Défense adverses."},
  block:{pp:5,name:'Barrage',type:'normal',cat:'status',power:0,accuracy:1,target:'foe',effect:{trap:true},desc:"Bloque la cible pour l'empêcher de fuir ou de switcher."},
  endeavor:{pp:5,name:'Effort',type:'normal',cat:'phys',power:0,accuracy:1,endeavor:true,desc:"Ramène les PV de la cible au même niveau que ceux du lanceur."},
  fakeout:{pp:10,name:'Bluff',type:'normal',cat:'phys',power:40,accuracy:1,priority:3,flinch:1.0,desc:"Une attaque surprise qui fait toujours peur à la cible."},
  weatherball:{pp:10,name:"Ball'Météo",type:'normal',cat:'phys',power:50,accuracy:1,desc:"Une sphère d'énergie dont la nature varie selon la météo."},
  smellingsalts:{pp:10,name:'Stimulant',type:'normal',cat:'phys',power:60,accuracy:1,desc:"Réveille les sens de la cible, particulièrement efficace contre la paralysie."},
  facade:{pp:20,name:'Façade',type:'normal',cat:'phys',power:70,accuracy:1,facadeBoost:true,desc:"Une attaque doublée de puissance si le lanceur a un problème de statut."},
  secretpower:{pp:20,name:'Force Cachée',type:'normal',cat:'phys',power:70,accuracy:1,secondaryStatus:{status:'paralysie',chance:0.3},desc:"Une capacité dont l'effet secondaire varie selon le terrain."},
  crushclaw:{pp:10,name:'Éclategriffe',type:'normal',cat:'phys',power:75,accuracy:0.95,secondaryBoost:{stat:'def',stages:-1,chance:0.5},desc:"Des griffes puissantes qui peuvent réduire la Défense adverse."},
  uproar:{pp:10,name:'Brouhaha',type:'normal',cat:'phys',power:90,accuracy:1,wakeAllOnHit:true,desc:"Un vacarme assourdissant qui réveille tous les Pokémon endormis."},
  hypervoice:{pp:10,name:'Mégaphone',type:'normal',cat:'spec',power:90,accuracy:1,desc:"Un cri surpuissant qui ébranle la cible."},
  aromatherapy:{pp:5,name:'Aromathérapi',type:'plante',cat:'status',power:0,target:'self',effect:{cureStatus:true},desc:"Un parfum apaisant qui soigne tout problème de statut."},
  grasswhistle:{pp:15,name:"Siffl'Herbe",type:'plante',cat:'status',power:0,target:'foe',accuracy:0.55,effect:{status:'sommeil'},desc:"Une douce mélodie qui endort la cible."},
  ingrain:{pp:20,name:'Racines',type:'plante',cat:'status',power:0,target:'self',effect:{ingrain:true},desc:"Plante des racines dans le sol pour récupérer des PV chaque tour."},
  bulletseed:{pp:30,name:'Balle Graine',type:'plante',cat:'phys',power:25,accuracy:1,desc:"Mitraille la cible de graines à répétition."},
  needlearm:{pp:15,name:'Poing Dard',type:'plante',cat:'phys',power:60,accuracy:1,flinch:0.3,desc:"Un coup végétal acéré qui peut faire peur à la cible."},
  magicalleaf:{pp:20,name:'Feuillemagik',type:'plante',cat:'spec',power:60,accuracy:1.0,desc:"Des feuilles magiques qui ne ratent presque jamais leur cible."},
  frenzyplant:{pp:5,name:'Végé-Attak',type:'plante',cat:'spec',power:150,accuracy:0.9,desc:"Des racines titanesques surgissent du sol pour écraser la cible."},
  poisonfang:{pp:15,name:'Crochetvenin',type:'poison',cat:'phys',power:50,accuracy:1,secondaryStatus:{status:'poison',chance:0.3},desc:"Une morsure venimeuse qui peut gravement empoisonner."},
  poisontail:{pp:25,name:'Queue-Poison',type:'poison',cat:'phys',power:50,accuracy:1,secondaryStatus:{status:'poison',chance:0.1},desc:"Un coup de queue empoisonné."},
  trick:{pp:10,name:'Tourmagik',type:'psy',cat:'status',power:0,accuracy:1,target:'foe',effect:{itemSwap:true},desc:"Échange son objet tenu avec celui de la cible."},
  roleplay:{pp:10,name:'Imitation',type:'psy',cat:'status',power:0,accuracy:1,target:'foe',effect:{abilityCopy:true},desc:"Copie le talent de la cible."},
  magiccoat:{pp:15,name:'Reflet Magik',type:'psy',cat:'status',power:0,target:'self',effect:{},desc:"Renvoie normalement la prochaine capacité de statut subie."},
  skillswap:{pp:10,name:'Échange',type:'psy',cat:'status',power:0,accuracy:1,target:'foe',effect:{abilitySwap:true},desc:"Échange son talent avec celui de la cible."},
  imprison:{pp:10,name:'Possessif',type:'psy',cat:'status',power:0,target:'self',effect:{},desc:"Empêche normalement la cible d'utiliser les capacités que le lanceur connaît aussi."},
  cosmicpower:{pp:20,name:'Force Cosmik',type:'psy',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'def',stages:1},{stat:'spd',stages:1}]},desc:"Puise dans une force mystique pour booster ses défenses."},
  calmmind:{pp:20,name:'Calmesprit',type:'psy',cat:'status',power:0,target:'self',effect:{selfBoost:[{stat:'spa',stages:1},{stat:'spd',stages:1}]},desc:"Une profonde méditation qui booste l'Attaque et la Défense Spéciales."},
  lusterpurge:{pp:5,name:'Lumi-Éclat',type:'psy',cat:'spec',power:70,accuracy:1,secondaryBoost:{stat:'spd',stages:-1,chance:0.5},desc:"Un éclat de lumière qui peut réduire la Défense Spéciale adverse."},
  mistball:{pp:5,name:"Ball'Brume",type:'psy',cat:'spec',power:70,accuracy:1,secondaryBoost:{stat:'spa',stages:-1,chance:0.5},desc:"Une sphère brumeuse qui peut réduire l'Attaque Spéciale adverse."},
  psychoboost:{pp:5,name:'Psycho Boost',type:'psy',cat:'spec',power:140,accuracy:0.9,selfBoost:[{stat:'spa',stages:-2}],desc:"Une explosion psychique dévastatrice qui affaiblit le lanceur."},
  rockblast:{pp:10,name:'Boule Roc',type:'roche',cat:'phys',power:25,accuracy:0.9,desc:"Projette une volée de rochers sur la cible."},
  rocktomb:{pp:15,name:'Tomberoche',type:'roche',cat:'phys',power:50,accuracy:0.8,secondaryBoost:{stat:'spe',stages:-1,chance:1.0},desc:"Des rochers qui immobilisent et ralentissent la cible."},
  sandtomb:{pp:15,name:'Tourbi-Sable',type:'sol',cat:'phys',power:35,accuracy:0.85,desc:"Emprisonne la cible dans un tourbillon de sable."},
  grudge:{pp:5,name:'Rancune',type:'fantome',cat:'status',power:0,target:'self',effect:{},desc:"Si le lanceur est mis K.O., la capacité responsable perd tous ses PP."},
  astonish:{pp:15,name:'Étonnement',type:'fantome',cat:'phys',power:30,accuracy:1,flinch:0.3,desc:"Un cri spectral soudain qui peut faire peur à la cible."},
  shadowpunch:{pp:20,name:'Poing Ombre',type:'fantome',cat:'phys',power:60,accuracy:1.0,desc:"Un poing spectral qui ne rate jamais sa cible."},
  torment:{pp:15,name:'Tourmente',type:'tenebres',cat:'status',power:0,accuracy:1,target:'foe',effect:{},desc:"Empêche normalement la cible d'utiliser deux fois la même capacité de suite."},
  flatter:{pp:15,name:'Flatterie',type:'tenebres',cat:'status',power:0,target:'foe',accuracy:1.0,effect:{status:'confusion',foeBoost:[{stat:'spa',stages:1}]},desc:"Flatte la cible pour la rendre confuse tout en boostant son Attaque Spéciale."},
  memento:{pp:10,name:'Souvenir',type:'tenebres',cat:'status',power:0,accuracy:1,target:'foe',effect:{selfFaintDebuff:true},desc:"Le lanceur se sacrifie pour affaiblir sévèrement la cible."},
  taunt:{pp:20,name:'Provoc',type:'tenebres',cat:'status',power:0,accuracy:1,target:'foe',effect:{tauntBlock:true},desc:"Provoque la cible pour l'empêcher d'utiliser des capacités de statut."},
  snatch:{pp:10,name:'Saisie',type:'tenebres',cat:'status',power:0,target:'self',effect:{},desc:"Vole normalement l'effet de la prochaine capacité non-offensive de l'adversaire."},
  faketears:{pp:20,name:'Croco Larme',type:'tenebres',cat:'status',power:0,target:'foe',accuracy:1.0,effect:{foeBoost:[{stat:'spd',stages:-2}]},desc:"De fausses larmes qui baissent fortement la Défense Spéciale adverse."},
  knockoff:{pp:20,name:'Sabotage',type:'tenebres',cat:'phys',power:20,accuracy:1,itemRemoveOnHit:true,desc:"Fait tomber l'objet tenu de la cible au contact."},
  featherdance:{pp:15,name:'Danse-Plume',type:'vol',cat:'status',power:0,target:'foe',accuracy:1.0,effect:{foeBoost:[{stat:'atk',stages:-2}]},desc:"Une pluie de plumes qui baisse fortement l'Attaque adverse."},
  aircutter:{pp:25,name:"Tranch'Air",type:'vol',cat:'phys',power:55,accuracy:0.95,desc:"Des lames d'air tranchantes."},
  aerialace:{pp:20,name:'Aéropique',type:'vol',cat:'phys',power:60,accuracy:1.0,desc:"Une attaque fulgurante qui ne rate presque jamais."},
  bounce:{pp:5,name:'Rebond',type:'vol',cat:'phys',power:85,accuracy:0.85,secondaryStatus:{status:'paralysie',chance:0.3},desc:"Bondit dans les airs avant de retomber sur la cible. Peut paralyser."}
};

function moveObj(id){ return MOVES[id]; }

