/* ==== pokemon/abilities.js (généré depuis index.html) ==== */
const ABILITY_DESC = {
  'Engrais':"Renforce les attaques Plante quand les PV sont bas.",
  'Chlorophylle':"Double la Vitesse sous un soleil intense.",
  'Brasier':"Renforce les attaques Feu quand les PV sont bas.",
  'Force Soleil':"Booste l'Attaque Spéciale sous un fort ensoleillement.",
  'Torrent':"Renforce les attaques Eau quand les PV sont bas.",
  'Cuvette':"Restaure un peu de PV à chaque tour sous la pluie.",
  'Peau Miracle':"Protège des altérations d'état au contact.",
  'Œil Composé':"Améliore fortement la précision des attaques.",
  'Essaim':"Renforce les attaques Insecte quand les PV sont bas.",
  'Regard Vif':"Empêche la baisse de précision et ignore l'évasion adverse.",
  'Pieds Fébriles':"Peut parfois faire trébucher le porteur sans raison.",
  'Fuite':"Permet de fuir ou d'éviter les combats sauvages plus facilement.",
  'Agitation':"Augmente la puissance physique mais réduit la précision.",
  'Sniper':"Renforce fortement les coups critiques.",
  'Intimidation':"Baisse l'Attaque de l'adversaire à l'entrée sur le terrain.",
  'Mue':"Peut guérir d'une altération d'état en changeant de peau.",
  'Statik':"Peut paralyser l'attaquant lors d'un contact.",
  'Paratonnerre':"Attire les attaques Électrik et les rend inoffensives.",
  'Voile Sable':"Augmente l'évasion pendant une tempête de sable.",
  'Baigne Sable':"Augmente la Vitesse pendant une tempête de sable.",
  'Point Poison':"Peut empoisonner l'attaquant lors d'un contact.",
  'Rivalité':"Frappe plus fort contre un adversaire du même genre.",
  'Joli Sourire':"Peut rendre amoureux l'attaquant lors d'un contact.",
  'Écran Poudre':"Empêche les altérations d'état secondaires.",
  'Torche':"Annule les attaques Feu et booste les siennes en retour.",
  'Momie':"Transmet parfois un effet en touchant l'adversaire.",
  'Battant':"Booste l'Attaque Spéciale quand une stat est abaissée.",
  'Télépathe':"Empêche d'être mis en confusion ou apeuré.",
  'Infiltration':"Ignore les effets de protection adverses comme le Mur Lumière.",
  'Pose Spore':"Peut empoisonner, endormir ou paralyser au contact.",
  'Peau Sèche':"Récupère des PV sous la pluie, en perd sous un fort soleil.",
  'Piège':"Empêche l'adversaire de fuir le combat.",
  'Ramassage':"Peut parfois trouver un objet après le combat.",
  'Technicien':"Renforce les attaques de faible puissance de base.",
  'Moiteur':"Empêche les attaques explosives de l'adversaire.",
  'Envelocape':"Protège des effets liés à la météo.",
  'Esprit Vital':"Empêche le sommeil.",
  'Colérique':"Met l'Attaque au maximum après un coup critique reçu.",
  'Absorbe-Eau':"Restaure des PV en étant touché par une attaque Eau.",
  'Coloforce':"Booste fortement l'Attaque, ignore les altérations d'état sur la puissance.",
  'Annule Garde':"Toutes les attaques touchent à coup sûr, dans les deux sens.",
  'Gloutonnerie':"Permet de consommer une baie plus tôt que prévu.",
  'Corps Sain':"Empêche la baisse de ses propres statistiques par l'adversaire.",
  'Suintement':"Renvoie des dégâts si touché par une capacité de drain.",
  'Tête de Roc':"Annule les dégâts de recul des attaques physiques.",
  'Solide Roc':"Survit avec 1 PV à une attaque qui mettrait normalement K.O.",
  'Corps Ardent':"Peut brûler l'attaquant lors d'un contact.",
  'Tempo Perso':"Empêche d'être mis en confusion.",
  'Régé-Force':"Restaure des PV en se retirant du combat.",
  'Benêt':"Empêche de tomber amoureux ou de paniquer.",
  'Magnépiège':"Empêche les Pokémon Acier ennemis de fuir.",
  'Matinal':"Se réveille deux fois plus vite en cas de sommeil.",
  'Isograisse':"Réduit de moitié les dégâts Feu et Glace reçus.",
  'Hydratation':"Soigne ses altérations d'état sous la pluie.",
  'Puanteur':"Peut apeurer l'adversaire au contact.",
  'Glu':"Empêche la perte ou le vol de l'objet tenu.",
  'Coque Armure':"Empêche de subir un coup critique.",
  'Multi-Coups':"Maximise toujours le nombre de coups des attaques multiples.",
  'Lévitation':"Rend totalement immunisé aux attaques Sol.",
  'Corps Maudit':"Peut bloquer la dernière capacité utilisée par l'adversaire.",
  'Insomnia':"Empêche totalement le sommeil.",
  'Hyper Cutter':"Empêche la baisse de l'Attaque par l'adversaire.",
  'Anti-Bruit':"Rend immunisé aux capacités sonores.",
  'Récolte':"Peut faire repousser une baie consommée après le combat.",
  'Gaz Inhibiteur':"Annule le talent de tous les Pokémon présents sur le terrain.",
  'Médic Nature':"Guérit automatiquement des altérations d'état en se retirant.",
  'Sérénité':"Double la chance de provoquer un effet secondaire.",
  'Feuille Garde':"Empêche les altérations d'état sous un fort ensoleillement.",
  'Audacieux':"Ignore les différences de niveau pour les dégâts et la capture.",
  'Glissade':"Double la Vitesse sous la pluie.",
  'Ignifu-Voile':"Empêche d'être brûlé.",
  'Lumiattirance':"Réduit l'évasion adverse et révèle les Pokémon à l'état sauvage.",
  'Filtre':"Réduit les dégâts des attaques super efficaces.",
  'Prédiction':"Révèle un type d'attaque que prépare l'adversaire.",
  'Brise Moule':"Ignore les talents défensifs de l'adversaire.",
  'Phobique':"Peut paniquer face à une attaque Tenebres ou Insecte.",
  'Adaptabilité':"Renforce considérablement le bonus de type (STAB).",
  'Pied Véloce':"Augmente la Vitesse en cas d'altération d'état.",
  'Absorbe-Volt':"Restaure des PV en étant touché par une attaque Électrik.",
  'Télécharge':"Augmente Attaque ou Attaque Spéciale selon la faiblesse adverse.",
  'Armurbaston':"Empêche de subir un coup critique.",
  'Pression':"Double les PP utilisés par l'adversaire lors de ses attaques.",
  'Vaccin':"Empêche d'être empoisonné.",
  'Rideau Neige':"Augmente l'évasion pendant la grêle.",
  'Écaille Spéciale':"Augmente fortement les chances de coup critique reçu... mais booste la Défense si touché.",
  'Trouble-Fête':"Empêche l'adversaire d'utiliser des capacités qui boostent ses stats.",
  'Synchro':"Transmet ses altérations d'état (poison, brûlure, paralysie) à l'attaquant.",
  'Échauffement':"Empêche d'être paralysé.",
  'Téméraire':"Met l'Attaque au maximum si touché par une attaque super efficace.",
  'Poing de Fer':"Renforce les attaques de poing.",
  'Calque':"Copie le talent du Pokémon adverse en combat.",

  /* ---- BLOC 1 (Gen 3) : talents manquants ---- */
  'Absentéisme':"Le Pokémon n'agit pas un tour sur deux.",
  'Air Lock':"Annule les effets de la météo tant que le Pokémon est sur le terrain.",
  'Armumagma':"Empêche d'être gelé.",
  'Attention':"Empêche de reculer de peur.",
  'Ciel Gris':"Annule les effets de la météo tant que le Pokémon est sur le terrain.",
  'Crachin':"Invoque la pluie à l'entrée sur le terrain.",
  'Cran':"Augmente l'Attaque de 50% en cas de problème de statut.",
  'Déguisement':"Change de type pour adopter celui de la dernière capacité offensive subie.",
  'Fermeté':"Survit toujours à 1 PV face à un coup qui l'aurait mis K.O. depuis les PV max, et immunise contre les capacités K.O. Direct.",
  'Force Pure':"Double l'Attaque du Pokémon.",
  'Garde Mystik':"Immunise contre toutes les capacités qui ne sont pas super efficaces.",
  'Marque Ombre':"Empêche l'adversaire de fuir ou de switcher.",
  'Météo':"Change de type selon la météo actuelle.",
  'Minus':"Augmente l'Attaque Spéciale si un allié possède le talent Plus.",
  'Peau Dure':"Blesse l'attaquant au contact.",
  'Plus':"Augmente l'Attaque Spéciale si un allié possède le talent Minus.",
  'Sable Volant':"Invoque une tempête de sable à l'entrée sur le terrain.",
  'Sécheresse':"Invoque un fort ensoleillement à l'entrée sur le terrain.",
  'Turbo':"Augmente la Vitesse d'un cran à la fin de chaque tour.",
  'Ventouse':"Empêche d'être forcé de quitter le combat.",
  'Écran Fumée':"Empêche les autres Pokémon de faire baisser les statistiques du porteur."
};

/* =================== DRESSEURS THÉMATIQUES =================== */
