/* ==== pokemon/abilities.js (généré depuis index.html) ==== */
const ABILITY_DESC = {
  /* ---- BLOC 1 (Gen 5) : talents manquants ---- */
  'Victorieux':"Augmente de 10% la précision des capacités du porteur (et de ses alliés en Combat Duo/Multi).",
  'Contestation':"Inverse les changements de statistiques subis.",
  'Luminescence':"Augmente le taux de rencontre de Pokémon sauvages et empêche la baisse de précision.",
  'Armure Rouillée':"Baisse la Défense mais augmente fortement la Vitesse si touché par une capacité physique.",
  'Cœur Soin':"Peut soigner l'altération de statut d'un allié voisin en Combat Duo/Trio ; sans effet en Combat Solo.",
  'Mode Zen':"Change de forme et de statistiques quand les PV passent sous la moitié.",
  'Défaitiste':"Diminue de moitié l'Attaque et l'Attaque Spéciale quand les PV passent sous la moitié.",
  'Illusion':"Se fait passer pour le dernier Pokémon de l'équipe jusqu'à subir des dégâts.",
  'Garde Magik':"Empêche de subir des dégâts autres que ceux des attaques directes.",
  'Herbivore':"Immunise contre les capacités Plante et booste l'Attaque Spéciale si touché.",
  'Épine de Fer':"Blesse l'attaquant au contact.",
  'Moins':"Augmente l'Attaque Spéciale si un allié possède le talent Plus.",
  'Turbo Brasier':"Ignore les talents défensifs de l'adversaire.",
  'Téra-Voltage':"Ignore les talents défensifs de l'adversaire.",
  'Engrais':"Renforce les attaques Plante quand les PV sont bas.",
  'Chlorophylle':"Double la Vitesse sous un soleil intense.",
  'Brasier':"Renforce les attaques Feu quand les PV sont bas.",
  'Force Soleil':"Booste l'Attaque Spéciale sous un fort ensoleillement.",
  'Torrent':"Renforce les attaques Eau quand les PV sont bas.",
  'Cuvette':"Restaure un peu de PV à chaque tour sous la pluie.",
  'Peau Miracle':"Protège des altérations d'état au contact.",
  'Œil Composé':"Améliore fortement la précision des attaques.",
  'Essaim':"Renforce les attaques Insecte quand les PV sont bas.",
  'Regard Vif':"Empêche la baisse de précision et ignore l'évasion adverse.",
  'Pieds Fébriles':"Peut parfois faire trébucher le porteur sans raison.",
  'Fuite':"Permet de fuir ou d'éviter les combats sauvages plus facilement.",
  'Agitation':"Augmente la puissance physique mais réduit la précision.",
  'Sniper':"Renforce fortement les coups critiques.",
  'Intimidation':"Baisse l'Attaque de l'adversaire à l'entrée sur le terrain.",
  'Mue':"Peut guérir d'une altération d'état en changeant de peau.",
  'Statik':"Peut paralyser l'attaquant lors d'un contact.",
  'Paratonnerre':"Attire les attaques Électrik et les rend inoffensives.",
  'Voile Sable':"Augmente l'évasion pendant une tempête de sable.",
  'Baigne Sable':"Augmente la Vitesse pendant une tempête de sable.",
  'Point Poison':"Peut empoisonner l'attaquant lors d'un contact.",
  'Rivalité':"Frappe plus fort contre un adversaire du même genre.",
  'Joli Sourire':"Peut rendre amoureux l'attaquant lors d'un contact.",
  'Écran Poudre':"Empêche les altérations d'état secondaires.",
  'Torche':"Annule les attaques Feu et booste les siennes en retour.",
  'Momie':"Transmet parfois un effet en touchant l'adversaire.",
  'Battant':"Booste l'Attaque Spéciale quand une stat est abaissée.",
  'Télépathe':"Empêche d'être mis en confusion ou apeuré.",
  'Infiltration':"Ignore les effets de protection adverses comme le Mur Lumière.",
  'Pose Spore':"Peut empoisonner, endormir ou paralyser au contact.",
  'Peau Sèche':"Récupère des PV sous la pluie, en perd sous un fort soleil.",
  'Piège':"Empêche l'adversaire de fuir le combat.",
  'Ramassage':"Peut parfois trouver un objet après le combat.",
  'Technicien':"Renforce les attaques de faible puissance de base.",
  'Moiteur':"Empêche les attaques explosives de l'adversaire.",
  'Envelocape':"Protège des effets liés à la météo.",
  'Esprit Vital':"Empêche le sommeil.",
  'Colérique':"Met l'Attaque au maximum après un coup critique reçu.",
  'Absorbe-Eau':"Restaure des PV en étant touché par une attaque Eau.",
  'Coloforce':"Booste fortement l'Attaque, ignore les altérations d'état sur la puissance.",
  'Annule Garde':"Toutes les attaques touchent à coup sûr, dans les deux sens.",
  'Gloutonnerie':"Permet de consommer une baie plus tôt que prévu.",
  'Corps Sain':"Empêche la baisse de ses propres statistiques par l'adversaire.",
  'Suintement':"Renvoie des dégâts si touché par une capacité de drain.",
  'Tête de Roc':"Annule les dégâts de recul des attaques physiques.",
  'Solide Roc':"Survit avec 1 PV à une attaque qui mettrait normalement K.O.",
  'Corps Ardent':"Peut brûler l'attaquant lors d'un contact.",
  'Tempo Perso':"Empêche d'être mis en confusion.",
  'Régé-Force':"Restaure des PV en se retirant du combat.",
  'Benêt':"Empêche de tomber amoureux ou de paniquer.",
  'Magnépiège':"Empêche les Pokémon Acier ennemis de fuir.",
  'Matinal':"Se réveille deux fois plus vite en cas de sommeil.",
  'Isograisse':"Réduit de moitié les dégâts Feu et Glace reçus.",
  'Hydratation':"Soigne ses altérations d'état sous la pluie.",
  'Puanteur':"Peut apeurer l'adversaire au contact.",
  'Glu':"Empêche la perte ou le vol de l'objet tenu.",
  'Coque Armure':"Empêche de subir un coup critique.",
  'Multi-Coups':"Maximise toujours le nombre de coups des attaques multiples.",
  'Lévitation':"Rend totalement immunisé aux attaques Sol.",
  'Corps Maudit':"Peut bloquer la dernière capacité utilisée par l'adversaire.",
  'Insomnia':"Empêche totalement le sommeil.",
  'Hyper Cutter':"Empêche la baisse de l'Attaque par l'adversaire.",
  'Anti-Bruit':"Rend immunisé aux capacités sonores.",
  'Récolte':"Peut faire repousser une baie consommée après le combat.",
  'Gaz Inhibiteur':"Annule le talent de tous les Pokémon présents sur le terrain.",
  'Médic Nature':"Guérit automatiquement des altérations d'état en se retirant.",
  'Sérénité':"Double la chance de provoquer un effet secondaire.",
  'Feuille Garde':"Empêche les altérations d'état sous un fort ensoleillement.",
  'Audacieux':"Ignore les différences de niveau pour les dégâts et la capture.",
  'Glissade':"Double la Vitesse sous la pluie.",
  'Ignifu-Voile':"Empêche d'être brûlé.",
  'Lumiattirance':"Réduit l'évasion adverse et révèle les Pokémon à l'état sauvage.",
  'Filtre':"Réduit les dégâts des attaques super efficaces.",
  'Prédiction':"Révèle un type d'attaque que prépare l'adversaire.",
  'Brise Moule':"Ignore les talents défensifs de l'adversaire.",
  'Phobique':"Peut paniquer face à une attaque Tenebres ou Insecte.",
  'Adaptabilité':"Renforce considérablement le bonus de type (STAB).",
  'Pied Véloce':"Augmente la Vitesse en cas d'altération d'état.",
  'Absorbe-Volt':"Restaure des PV en étant touché par une attaque Électrik.",
  'Télécharge':"Augmente Attaque ou Attaque Spéciale selon la faiblesse adverse.",
  'Armurbaston':"Empêche de subir un coup critique.",
  'Pression':"Double les PP utilisés par l'adversaire lors de ses attaques.",
  'Vaccin':"Empêche d'être empoisonné.",
  'Rideau Neige':"Augmente l'évasion pendant la grêle.",
  'Écaille Spéciale':"Augmente fortement les chances de coup critique reçu... mais booste la Défense si touché.",
  'Trouble-Fête':"Empêche l'adversaire d'utiliser des capacités qui boostent ses stats.",
  'Synchro':"Transmet ses altérations d'état (poison, brûlure, paralysie) à l'attaquant.",
  'Échauffement':"Empêche d'être paralysé.",
  'Téméraire':"Met l'Attaque au maximum si touché par une attaque super efficace.",
  'Poing de Fer':"Renforce les attaques de poing.",
  'Calque':"Copie le talent du Pokémon adverse en combat.",

  /* ---- BLOC 1 (Gen 3) : talents manquants ---- */
  'Absentéisme':"Le Pokémon n'agit pas un tour sur deux.",
  'Air Lock':"Annule les effets de la météo tant que le Pokémon est sur le terrain.",
  'Armumagma':"Empêche d'être gelé.",
  'Attention':"Empêche de reculer de peur.",
  'Ciel Gris':"Annule les effets de la météo tant que le Pokémon est sur le terrain.",
  'Crachin':"Invoque la pluie à l'entrée sur le terrain.",
  'Cran':"Augmente l'Attaque de 50% en cas de problème de statut.",
  'Déguisement':"Change de type pour adopter celui de la dernière capacité offensive subie.",
  'Fermeté':"Survit toujours à 1 PV face à un coup qui l'aurait mis K.O. depuis les PV max, et immunise contre les capacités K.O. Direct.",
  'Force Pure':"Double l'Attaque du Pokémon.",
  'Garde Mystik':"Immunise contre toutes les capacités qui ne sont pas super efficaces.",
  'Marque Ombre':"Empêche l'adversaire de fuir ou de switcher.",
  'Météo':"Change de type selon la météo actuelle.",
  'Minus':"Augmente l'Attaque Spéciale si un allié possède le talent Plus.",
  'Peau Dure':"Blesse l'attaquant au contact.",
  'Plus':"Augmente l'Attaque Spéciale si un allié possède le talent Minus.",
  'Sable Volant':"Invoque une tempête de sable à l'entrée sur le terrain.",
  'Sécheresse':"Invoque un fort ensoleillement à l'entrée sur le terrain.",
  'Turbo':"Augmente la Vitesse d'un cran à la fin de chaque tour.",
  'Ventouse':"Empêche d'être forcé de quitter le combat.",
  'Écran Fumée':"Empêche les autres Pokémon de faire baisser les statistiques du porteur.",

  /* ---- BLOC 2 (Gen 4) : talents manquants ---- */
  'Alerte Neige':"Invoque la grêle à l'entrée sur le terrain.",
  'Anticipation':"Frissonne si un adversaire connaît une capacité pouvant sévèrement blesser le porteur.",
  'Boom Final':"Si le porteur est mis K.O. par une capacité de contact, l'attaquant perd la moitié de ses PV max.",
  'Chanceux':"Augmente le taux de coups critiques du porteur.",
  'Cherche Miel':"Permet parfois de récolter du Miel après un combat.",
  'Corps Gel':"Récupère un peu de PV chaque tour sous la grêle.",
  'Début Calme':"Divise par deux l'Attaque et la Vitesse pendant les 5 premiers tours.",
  'Délestage':"Booste la Vitesse du porteur si son objet tenu est consommé ou volé.",
  'Don Floral':"Booste l'Attaque et la Défense Spéciale de l'équipe sous un fort ensoleillement.",
  'Fouille':"Révèle l'objet tenu par l'adversaire à l'entrée en combat.",
  'Ignifugé':"Réduit de moitié les dégâts des capacités de type Feu et immunise contre la brûlure.",
  'Impassible':"Booste la Vitesse à chaque fois que le porteur recule de peur.",
  'Inconscient':"Ignore les changements de statistiques de l'adversaire lors du calcul des dégâts.",
  'Lavabo':"Attire les capacités de type Eau et booste l'Attaque Spéciale au lieu d'en subir les dégâts.",
  'Lentiteintée':"Booste la puissance des capacités peu efficaces.",
  'Maladresse':"Empêche d'utiliser l'objet tenu.",
  'Mauvais Rêve':"Inflige des dégâts aux adversaires endormis à chaque tour.",
  'Motorisé':"Immunise contre les capacités Électrik et booste la Vitesse si le porteur est touché.",
  'Multi-Type':"Change le type du porteur selon la Plaque qu'il tient.",
  'Pieds Confus':"Augmente l'esquive du porteur s'il est confus.",
  'Soin Poison':"Récupère des PV au lieu d'en perdre si le porteur est empoisonné.",
  'Simple':"Double l'effet des changements de statistiques du porteur.",
  'Toxitouche':"Peut empoisonner la cible au contact.",
  'Analyste':"Booste la puissance des capacités utilisées en dernier ce tour-ci.",
  'Sans Limite':"Supprime les effets secondaires de ses capacités pour en booster la puissance.",
  'Cœur Noble':"Booste l'Attaque quand le porteur subit une capacité de type Ténèbres.",
  'Farceur':"Augmente la priorité des capacités de statut du porteur.",
  'Acharné':"Booste fortement l'Attaque quand une de ses statistiques est réduite par l'adversaire.",
  'Force Sable':"Booste la puissance des capacités Sol, Roche et Acier pendant une tempête de sable.",
  'Glu':"Empêche l'adversaire de voler ou d'échanger l'objet tenu par le porteur.",
  'Impudence':"Booste l'Attaque après avoir mis K.O. un adversaire.",
  'Cœur de Coq':"Empêche la réduction de la Défense du porteur.",
  'Tension':"Empêche les Pokémon adverses de manger leur Baie.",
  'Pickpocket':"Vole l'objet tenu de l'attaquant après avoir subi une capacité de contact."
};

/* =================== DRESSEURS THÉMATIQUES =================== */
