/* ==== Pokédex n°152 à 251 (Johto), lignées classiques en ordre de Pokédex.
   DEX_NUMBERS_GEN2 (numéros de Pokédex, pour les sprites) est à la fin du fichier. ==== */
const LINES_GEN2 = [
{id:'chikorita',abilities:['Engrais','Feuille Garde'],moveIds:['tackle','razorleaf','bodyslam','reflect','safeguard','synthesis','solarbeam','lightscreen','gigadrain','headbutt','rocksmash','protect','swordsdance','doubleteam','endure','bulletseed','hyperbeam','knockoff','doubleedge','earthquake','bulldoze','irontail','curse','dazzlinggleam','outrage','facade','ancientpower','petaldance','frenzyplant','growl','petalblizzard','poisonpowder','magicalleaf','sweetscent','sleeptalk','takedown','charm','faketears','mudslap','sunnyday','zenheadbutt','encore','grassyterrain','rest','weatherball','endeavor','leafblade','counter','mimic','snore','swagger','furycutter','magiccoat','vinewhip','flail','ingrain','refresh','aromatherapy','grasswhistle','laserfocus','stompingtantrum','leechseed','substitute','helpinghand','naturalgift','wringout','worryseed','seedbomb','energyball','leafstorm','captivate','grassknot','round','echoedvoice','healpulse','grasspledge','workup','terablast','earthpower','gigaimpact','rockclimb','dragontail'],
 stages:[
  {name:'Germignon',types:['plante'],base:st(45,49,65,49,65,45)},
  {name:'Macronium',types:['plante'],base:st(60,62,80,63,80,60)},
  {name:'Méganium',types:['plante'],base:st(80,82,100,83,100,80),forms:{
    meganiumite:{name:'Méga-Méganium',types:['plante','fee'],base:st(80,92,115,143,115,80),abilities:['Zénith Suprême']}
  }}]},
{id:'cyndaquil',abilities:['Brasier','Torche'],moveIds:['doubleedge','ember','eruption','leer','smokescreen','tackle','quickattack','flamewheel','defensecurl','swift','flamethrower','overheat','curse','doublekick','extrasensory','howl','reversal','takedown','protect','lowkick','firespin','facade','aerialace','bulldoze','brickbreak','zenheadbutt','shadowclaw','bodyslam','firepunch','thunderpunch','sleeptalk','rest','rockslide','ironhead','willowisp','shadowball','heatwave','playrough','fireblast','earthquake','blastburn','focusblast','hyperbeam','solarbeam','confuseray','nightshade','calmmind','endeavor','spite','burnup','rollout','firefang','headbutt','mimic','snore','mudslap','endure','swagger','thrash','submission','furyswipes','foresight','crushclaw','furycutter','focuspunch','megapunch','megakick','counter','seismictoss','dynamicpunch','laserfocus','throatchop','stompingtantrum','roar','substitute','naturalgift','flareblitz','lavaplume','captivate','flameburst','flamecharge','round','incinerate','inferno','firepledge','workup','wildcharge','terablast','temperflare','helpinghand','gyroball','fling','gigaimpact','rockclimb','hex','covet'],
 stages:[
  {name:'Héricendre',types:['feu'],base:st(39,52,43,60,50,65)},
  {name:'Feurisson',types:['feu'],base:st(58,64,58,80,65,80)},
  {name:'Typhlosion',types:['feu'],base:st(78,84,78,109,85,100)}]},
{id:'totodile',abilities:['Torrent','Sans Limite'],moveIds:['agility','aerialace','ancientpower','aquatail','bite','blizzard','bodyslam','brickbreak','bulldoze','crunch','curse','dig','doubleedge','doubleteam','dragonclaw','dragondance','earthquake','endeavor','endure','facade','faketears','focusblast','focuspunch','hydropump','hyperbeam','icebeam','icefang','icepunch','icywind','leer','lowkick','mudslap','muddywater','metalclaw','outrage','protect','raindance','razorwind','rest','rockslide','rocksmash','rocktomb','scaryface','screech','shadowclaw','slash','sleeptalk','swordsdance','superpower','surf','takedown','thief','thrash','watergun','waterfall','waterpulse','whirlpool','scratch','flail','megapunch','megakick','headbutt','counter','seismictoss','mimic','snore','spite','swagger','dynamicpunch','irontail','uproar','dive','block','flatter','watersport','furycutter','hydrocannon','dragonpulse','liquidation','substitute','mudsport','naturalgift','fling','captivate','aquajet','honeclaws','round','chipaway','scald','waterpledge','workup','terablast','chillingwater','roar','helpinghand','gigaimpact','avalanche','rockclimb','dragontail','snarl'],
 stages:[
  {name:'Kaiminus',types:['eau'],base:st(50,65,64,44,48,43)},
  {name:'Crocrodil',types:['eau'],base:st(65,80,80,59,63,58)},
  {name:'Aligatueur',types:['eau'],base:st(85,105,100,79,83,78),forms:{
    feraligite:{name:'Méga-Aligatueur',types:['eau','dragon'],base:st(85,160,125,89,93,78),abilities:['Dracomorphose']}
  }}]},
{id:'sentret',abilities:['Fuite','Regard Vif','Fouille'],moveIds:['defensecurl','quickattack','scratch','furyswipes','slam','rest','suckerpunch','amnesia','batonpass','doubleedge','hypervoice','agility','takedown','charm','protect','waterpulse','thief','facade','swift','endure','sunnyday','raindance','dig','brickbreak','zenheadbutt','uturn','shadowclaw','bodyslam','firepunch','thunderpunch','icepunch','sleeptalk','trick','shadowball','surf','flamethrower','thunderbolt','playrough','reversal','icebeam','blizzard','hyperbeam','focusblast','thunder','solarbeam','knockoff','superfang','uproar','focuspunch','endeavor','headbutt','mimic','snore','mudslap','rollout','swagger','furycutter','dynamicpunch','irontail','shockwave','aquatail','focusenergy','slash','pursuit','assist','babydolleyes','substitute','followme','helpinghand','naturalgift','fling','mefirst','lastresort','seedbomb','captivate','grassknot','chargebeam','honeclaws','round','echoedvoice','retaliate','workup','terablast','tidyup','chillingwater','gigaimpact','coil','covet'],
 stages:[
  {name:'Fouinette',types:['normal'],base:st(35,46,34,35,45,20)},
  {name:'Fouinar',types:['normal'],base:st(85,76,64,45,55,90)}]},
{id:'hoothoot',abilities:['Insomnia','Regard Vif','Lentiteintée'],moveIds:['growl','peck','skyattack','tackle','confusion','reflect','airslash','extrasensory','takedown','uproar','moonblast','hypnosis','dreameater','agility','scaryface','protect','psybeam','confuseray','thief','facade','aerialace','swift','aircutter','nightshade','endure','sunnyday','raindance','zenheadbutt','bodyslam','sleeptalk','rest','imprison','fly','skillswap','shadowball','hypervoice','heatwave','psychic','amnesia','calmmind','hurricane','hyperbeam','haze','spite','psychup','doubleedge','featherdance','futuresight','curse','mimic','nightmare','snore','mudslap','swagger','twister','magiccoat','recycle','dualwingbeat','wingattack','whirlwind','supersonic','mirrormove','feintattack','meanlook','laserfocus','substitute','roost','naturalgift','pluck','tailwind','psychoshift','bravebird','nastyplot','defog','captivate','ominouswind','synchronoise','round','echoedvoice','storedpower','acrobatics','workup','terablast','gigaimpact'],
 stages:[
  {name:'Hoothoot',types:['normal','vol'],base:st(60,30,30,36,56,50)},
  {name:'Noarfang',types:['normal','vol'],base:st(100,50,50,76,96,70)}]},
{id:'ledyba',abilities:['Essaim','Matinal','Phobique'],moveIds:['supersonic','swift','tackle','lightscreen','reflect','safeguard','machpunch','batonpass','agility','airslash','doubleedge','bugbite','counter','encore','knockoff','psybeam','screech','focuspunch','sunnyday','hyperbeam','protect','gigadrain','solarbeam','dig','brickbreak','doubleteam','aerialace','facade','rest','attract','thief','focusblast','endure','swordsdance','sleeptalk','swagger','uturn','strength','rocksmash','cometpunch','silverwind','icepunch','thunderpunch','megapunch','headbutt','stringshot','mimic','snore','rollout','dynamicpunch','uproar','aircutter','bide','dizzypunch','substitute','roost','naturalgift','tailwind','fling','bugbuzz','drainpunch','captivate','ominouswind','round','acrobatics','strugglebug','gigaimpact','defog'],
 stages:[
  {name:'Coxy',types:['insecte','vol'],base:st(40,20,30,40,80,55)},
  {name:'Coxyclaque',types:['insecte','vol'],base:st(55,35,50,55,110,85),abilities:['Essaim','Matinal','Poing de Fer']}]},
{id:'spinarak',abilities:['Essaim','Insomnia','Sniper'],moveIds:['toxicspikes','absorb','agility','bodyslam','bugbite','dig','endure','facade','fellstinger','furyswipes','gigadrain','hyperbeam','infestation','knockoff','leechlife','megahorn','nightshade','pinmissile','poisonjab','poisonsting','protect','psychic','scaryface','sleeptalk','sludgebomb','stringshot','suckerpunch','sunnyday','swordsdance','thief','toxic','focusenergy','stickyweb','screech','spite','rest','batonpass','toxicthread','doubleedge','mimic','snore','swagger','signalbeam','bounce','twineedle','sonicboom','disable','psybeam','pursuit','nightslash','lunge','throatchop','stompingtantrum','substitute','naturalgift','xscissor','bugbuzz','crosspoison','captivate','honeclaws','venoshock','ragepowder','sludgewave','acidspray','foulplay','round','hex','strugglebug','electroweb','terablast','pounce','assurance','gigaimpact','shadowsneak'],
 stages:[
  {name:'Mimigal',types:['insecte','poison'],base:st(40,60,40,40,40,30)},
  {name:'Migalos',types:['insecte','poison'],base:st(70,90,70,60,70,40)}]},
{id:'chinchou',abilities:['Absorbe-Volt','Lumiattirance','Absorbe-Eau'],moveIds:['eerieimpulse','supersonic','thunderwave','watergun','bubblebeam','confuseray','spark','charge','discharge','flail','takedown','hydropump','spitup','stockpile','swallow','agility','protect','waterpulse','psybeam','facade','icywind','endure','raindance','sleeptalk','waterfall','dazzlinggleam','rest','surf','thunderbolt','amnesia','icebeam','electricterrain','blizzard','hyperbeam','thunder','whirlpool','muddywater','curse','doubleedge','mimic','snore','swagger','healbell','dive','signalbeam','bounce','shockwave','suckerpunch','risingvoltage','mist','screech','aquatail','substitute','brine','naturalgift','aquaring','captivate','chargebeam','electroball','soak','round','scald','voltswitch','electroweb','wildcharge','iondeluge','terablast','chillingwater','gigaimpact','spotlight'],
 stages:[
  {name:'Loupio',types:['eau','electrik'],base:st(75,38,38,56,56,67)},
  {name:'Lanturn',types:['eau','electrik'],base:st(125,58,58,76,76,67)}]},
{id:'togepi',abilities:['Agitation','Sérénité','Chanceux'],moveIds:['tackle','fairywind','aircutter','drainingkiss','calmmind','airslash','babydolleyes','extrasensory','moonblast','aerialace','dazzlinggleam','flamethrower','hyperbeam','magicalleaf','mysticalfire','playrough','psychic','rest','rocksmash','shadowball','swift','triattack','waterpulse','zenheadbutt','megapunch','megakick','headbutt','bodyslam','doubleedge','counter','seismictoss','thunderwave','mimic','defensecurl','metronome','softboiled','dreameater','snore','mudslap','endure','rollout','swagger','sleeptalk','healbell','psychup','ancientpower','uproar','trick','magiccoat','endeavor','hypervoice','signalbeam','shockwave','peck','mirrormove','foresight','present','morningsun','futuresight','secretpower','skyattack','twister','heatwave','focuspunch','dualwingbeat','laserfocus','substitute','followme','helpinghand','naturalgift','fling','psychoshift','luckychant','lastresort','nastyplot','captivate','grassknot','psyshock','telekinesis','afteryou','round','echoedvoice','storedpower','incinerate','bestow','workup','roost','tailwind','drainpunch','gigaimpact','defog','ominouswind','retaliate','pluck','allyswitch','covet'],
 stages:[
  {name:'Togepi',types:['fee'],base:st(35,20,65,40,65,20)},
  {name:'Togetic',types:['fee','vol'],base:st(55,40,85,80,105,40)},
  {name:'Togekiss',types:['fee','vol'],base:st(85,50,95,120,115,80)}]},
{id:'natu',abilities:['Synchro','Matinal','Rebond'],moveIds:['airslash','leer','peck','teleport','confuseray','nightshade','psychic','wish','futuresight','drillpeck','featherdance','haze','quickattack','suckerpunch','zenheadbutt','calmmind','sunnyday','hyperbeam','lightscreen','protect','raindance','gigadrain','dazzlinggleam','solarbeam','shadowball','doubleteam','reflect','aerialace','facade','rest','attract','thief','steelwing','skillswap','endure','thunderwave','psychup','sleeptalk','dreameater','swagger','uturn','fly','doubleedge','mimic','swift','skyattack','nightmare','snore','painsplit','twister','heatwave','trick','magiccoat','aircutter','signalbeam','expandingforce','dualwingbeat','feintattack','refresh','laserfocus','substitute','roost','miracleeye','naturalgift','pluck','tailwind','psychoshift','luckychant','mefirst','powerswap','guardswap','trickroom','captivate','grassknot','ominouswind','psyshock','telekinesis','magicroom','synchronoise','simplebeam','round','storedpower','allyswitch','gigaimpact','defog','foulplay'],
 stages:[
  {name:'Natu',types:['psy','vol'],base:st(40,50,45,70,45,70)},
  {name:'Xatu',types:['psy','vol'],base:st(65,75,70,95,70,95)}]},
{id:'mareep',abilities:['Statik','Plus'],moveIds:['growl','tackle','thundershock','thunderwave','charge','confuseray','thunderbolt','lightscreen','thunder','zapcannon','eerieimpulse','brickbreak','protect','swift','dig','firepunch','reflect','bodyslam','endure','discharge','hyperbeam','agility','doubleedge','dragonpulse','dazzlinggleam','outrage','focusblast','facade','takedown','cottonspore','electricterrain','flatter','lowkick','bulldoze','sunnyday','raindance','sleeptalk','rest','endeavor','thunderpunch','icepunch','headbutt','mimic','defensecurl','snore','swagger','healbell','irontail','signalbeam','shockwave','sandattack','screech','safeguard','odorsleuth','megapunch','megakick','counter','seismictoss','dynamicpunch','focuspunch','laserfocus','substitute','helpinghand','naturalgift','magnetrise','powergem','captivate','chargebeam','electroball','afteryou','round','echoedvoice','voltswitch','electroweb','wildcharge','cottonguard','terablast','roar','fling','gigaimpact','rockclimb','dragontail','iondeluge','magneticflux','dragoncheer'],
 stages:[
  {name:'Wattouat',types:['electrik'],base:st(55,40,40,65,45,35)},
  {name:'Lainergie',types:['electrik'],base:st(70,55,55,80,60,45)},
  {name:'Pharamp',types:['electrik'],base:st(90,75,85,115,90,55),forms:{
    pharampite:{name:'Méga-Pharamp',types:['electrik','dragon'],base:st(90,95,105,165,110,45),abilities:['Brise Moule']}
  }}]},
{id:'marill',abilities:['Isograisse','Coloforce','Herbivore'],moveIds:['defensecurl','rollout','tackle','tailwhip','watergun','bubblebeam','charm','slam','aquatail','playrough','raindance','hydropump','doubleedge','superpower','bellydrum','perishsong','present','sing','supersonic','tickle','takedown','faketears','mudslap','protect','waterpulse','disarmingvoice','facade','bulldoze','swift','icywind','mudshot','drainingkiss','endure','dig','brickbreak','bodyslam','icepunch','sleeptalk','lightscreen','waterfall','metronome','rest','hypervoice','encore','surf','amnesia','icebeam','mistyterrain','blizzard','focusblast','hyperbeam','knockoff','focuspunch','whirlpool','muddywater','splash','bounce','headbutt','mimic','snore','swagger','irontail','uproar','refresh','camouflage','watersport','megapunch','megakick','seismictoss','dynamicpunch','dive','steelroller','mistyexplosion','foresight','futuresight','liquidation','substitute','helpinghand','naturalgift','copycat','captivate','aquajet','soak','round','scald','workup','terablast','fling','aquaring','grassknot','icespinner','snowscape','chillingwater','gigaimpact','covet'],
 stages:[
  {name:'Azurill',types:['normal','fee'],base:st(50,20,40,20,40,20)},
  {name:'Marill',types:['eau','fee'],base:st(70,20,50,20,50,40)},
  {name:'Azumarill',types:['eau','fee'],base:st(100,50,80,50,80,50)}]},
{id:'sudowoodo',abilities:['Fermeté','Tête de Roc','Phobique'],moveIds:['faketears','flail','rockthrow','stoneedge','suckerpunch','rockslide','lowkick','counter','doubleedge','slam','curse','defensecurl','harden','headbutt','rollout','takedown','mudslap','protect','thief','facade','bulldoze','mudshot','rockblast','endure','sunnyday','sandstorm','dig','brickbreak','bodyslam','firepunch','thunderpunch','icepunch','sleeptalk','rest','taunt','spikes','irondefense','stealthrock','calmmind','earthquake','hyperbeam','focuspunch','psychup','endeavor','mimic','rocktomb','block','tearfullook','snore','uproar','roleplay','stompingtantrum','selfdestruct','sandtomb','megapunch','megakick','seismictoss','explosion','swagger','dynamicpunch','meteorbeam','substitute','helpinghand','naturalgift','copycat','rockpolish','powergem','earthpower','captivate','grassknot','headsmash','smackdown','foulplay','afteryou','round','terablast','hammerarm','fling','drainpunch','gigaimpact','woodhammer','lowsweep','covet'],
 stages:[
  {name:'Manzaï',types:['roche'],base:st(50,80,95,10,45,10)},
  {name:'Simularbre',types:['roche'],base:st(70,100,115,30,65,30)}]},
{id:'hoppip',abilities:['Chlorophylle','Feuille Garde','Infiltration'],moveIds:['absorb','splash','synthesis','tailwhip','tackle','fairywind','poisonpowder','sleeppowder','stunspore','bulletseed','megadrain','cottonspore','uturn','gigadrain','encore','grassyterrain','takedown','charm','protect','thief','facade','aerialace','magicalleaf','endure','sunnyday','raindance','sleeptalk','reflect','lightscreen','dazzlinggleam','rest','swordsdance','hyperbeam','solarbeam','doubleedge','endeavor','memento','bounce','headbutt','mimic','defensecurl','snore','swagger','payday','growl','confusion','amnesia','psychup','aromatherapy','strengthsap','leechseed','substitute','helpinghand','naturalgift','tailwind','fling','worryseed','seedbomb','energyball','switcheroo','leafstorm','captivate','grassknot','ragepowder','round','acrobatics','cottonguard','terablast','gigaimpact'],
 stages:[
  {name:'Granivol',types:['plante','vol'],base:st(35,35,40,35,55,50)},
  {name:'Floravol',types:['plante','vol'],base:st(55,45,50,45,65,80)},
  {name:'Cotovol',types:['plante','vol'],base:st(75,55,70,55,95,110)}]},
{id:'aipom',abilities:['Fuite','Ramassage','Multi-Coups'],moveIds:['astonish','sandattack','scratch','tailwhip','batonpass','tickle','furyswipes','swift','screech','agility','takedown','mudslap','protect','waterpulse','lowkick','thief','facade','aerialace','mudshot','endure','sunnyday','raindance','dig','brickbreak','uturn','shadowclaw','firepunch','thunderpunch','icepunch','sleeptalk','metronome','thunderwave','rest','taunt','shadowball','thunderbolt','hyperbeam','thunder','solarbeam','spite','knockoff','focuspunch','doubleedge','endeavor','megapunch','megakick','headbutt','bodyslam','counter','seismictoss','mimic','defensecurl','dreameater','nightmare','snore','swagger','furycutter','dynamicpunch','irontail','uproar','roleplay','snatch','bounce','shockwave','doubleslap','slam','pursuit','beatup','fakeout','revenge','laserfocus','substitute','helpinghand','naturalgift','payback','fling','lastresort','seedbomb','switcheroo','nastyplot','mudbomb','gunkshot','captivate','grassknot','doublehit','honeclaws','smackdown','lowsweep','foulplay','round','quickguard','acrobatics','retaliate','workup','tailslap','terablast','chillingwater','gigaimpact','dualchop','covet'],
 stages:[
  {name:'Capumain',types:['normal'],base:st(55,70,55,40,55,85)},
  {name:'Capidextre',types:['normal'],base:st(75,100,66,60,66,115),abilities:['Technicien','Ramassage','Multi-Coups']}]},
{id:'sunkern',abilities:['Chlorophylle','Force Soleil','Matinal'],moveIds:['growth','pound','tackle','ingrain','absorb','megadrain','razorleaf','gigadrain','bulletseed','petaldance','solarbeam','doubleedge','sunnyday','petalblizzard','curse','encore','grassyterrain','morningsun','takedown','protect','facade','magicalleaf','endure','raindance','sleeptalk','lightscreen','dazzlinggleam','rest','swordsdance','sludgebomb','hyperbeam','weatherball','synthesis','endeavor','mimic','snore','swagger','uproar','bide','sweetscent','grasswhistle','leechseed','substitute','helpinghand','naturalgift','worryseed','seedbomb','energyball','earthpower','leafstorm','captivate','grassknot','afteryou','round','terablast','gigaimpact','flowershield'],
 stages:[
  {name:'Tournegrin',types:['plante'],base:st(30,30,30,30,30,30)},
  {name:'Héliatronc',types:['plante'],base:st(75,75,55,105,85,30)}]},
{id:'yanma',abilities:['Turbo','Œil Composé','Fouille'],moveIds:['airslash','doubleteam','nightslash','tackle','quickattack','detect','supersonic','uproar','bugbite','ancientpower','slash','screech','uturn','hypnosis','takedown','scaryface','protect','thief','facade','aerialace','swift','aircutter','endure','sunnyday','sleeptalk','rest','swordsdance','leechlife','crunch','gigadrain','shadowball','psychic','reversal','hyperbeam','solarbeam','psychup','doubleedge','wingattack','headbutt','stringshot','mimic','dreameater','snore','swagger','signalbeam','whirlwind','feintattack','pursuit','secretpower','silverwind','mudslap','laserfocus','substitute','roost','naturalgift','feint','tailwind','bugbuzz','defog','captivate','ominouswind','round','strugglebug','terablast','pounce','gigaimpact'],
 stages:[
  {name:'Yanma',types:['insecte','vol'],base:st(65,65,45,75,45,95)},
  {name:'Yanmega',types:['insecte','vol'],base:st(86,76,86,116,56,95),abilities:['Turbo','Lentiteintée','Fouille']}]},
{id:'wooper',abilities:['Moiteur','Absorbe-Eau','Inconscient'],moveIds:['mudshot','raindance','tailwhip','watergun','haze','mist','slam','yawn','aquatail','muddywater','amnesia','toxic','earthquake','ancientpower','counter','curse','doublekick','recover','spitup','stockpile','swallow','takedown','mudslap','protect','waterpulse','thief','facade','bulldoze','icywind','rocktomb','endure','sandstorm','dig','brickbreak','bodyslam','icepunch','sleeptalk','waterfall','rest','rockslide','spikes','surf','icebeam','hydropump','blizzard','sludgebomb','stoneedge','focusblast','hyperbeam','focuspunch','doubleedge','whirlpool','headbutt','mimic','defensecurl','snore','rollout','swagger','dynamicpunch','irontail','dive','stompingtantrum','safeguard','encore','eerieimpulse','poweruppunch','megapunch','megakick','seismictoss','substitute','helpinghand','mudsport','naturalgift','guardswap','earthpower','avalanche','mudbomb','captivate','sludgewave','acidspray','afteryou','round','scald','terablast','snowscape','chillingwater','fling','drainpunch','gigaimpact'],
 stages:[
  {name:'Axoloto',types:['eau','sol'],base:st(55,45,45,25,25,15)},
  {name:'Maraiste',types:['eau','sol'],base:st(95,85,85,65,65,35)}]},
{id:'murkrow',abilities:['Insomnia','Chanceux','Farceur'],moveIds:['astonish','haze','nightslash','suckerpunch','wingattack','swagger','darkpulse','confuseray','drillpeck','featherdance','flatter','perishsong','screech','skyattack','whirlwind','takedown','scaryface','protect','thief','facade','aerialace','icywind','aircutter','nightshade','endure','sunnyday','raindance','uturn','airslash','sleeptalk','thunderwave','rest','taunt','shadowball','heatwave','psychic','calmmind','hurricane','hyperbeam','spite','uproar','psychup','doubleedge','endeavor','fly','gust','peck','meanlook','torment','comeuppance','mimic','swift','dreameater','nightmare','snore','mudslap','twister','snatch','quickattack','mirrormove','feintattack','superpower','substitute','roost','naturalgift','pluck','tailwind','payback','assurance','embargo','psychoshift','punishment','bravebird','gigaimpact','nastyplot','defog','captivate','ominouswind','foulplay','round','hex','quash','acrobatics','retaliate','snarl','terablast','helpinghand','incinerate','chillingwater'],
 stages:[
  {name:'Cornèbre',types:['tenebres','vol'],base:st(60,85,42,85,42,91)},
  {name:'Corboss',types:['tenebres','vol'],base:st(100,125,52,105,52,71),abilities:['Insomnia','Chanceux','Impudence']}]},
{id:'misdreavus',abilities:['Lévitation'],moveIds:['astonish','growl','magicalleaf','mysticalfire','phantomforce','spite','curse','destinybond','imprison','memento','screech','suckerpunch','charm','faketears','scaryface','protect','psybeam','confuseray','thief','facade','swift','icywind','drainingkiss','nightshade','endure','sunnyday','raindance','sleeptalk','dazzlinggleam','thunderwave','rest','taunt','darkpulse','skillswap','willowisp','trick','shadowball','hypervoice','psychic','thunderbolt','calmmind','hyperbeam','thunder','futuresight','confusion','perishsong','meanlook','painsplit','headbutt','doubleedge','mimic','defensecurl','dreameater','nightmare','snore','swagger','healbell','psychup','uproar','magiccoat','snatch','shockwave','laserfocus','substitute','helpinghand','naturalgift','payback','embargo','mefirst','powergem','energyball','gigaimpact','nastyplot','trickroom','captivate','grassknot','chargebeam','ominouswind','wonderroom','psyshock','telekinesis','magicroom','foulplay','round','echoedvoice','storedpower','allyswitch','hex','terablast','snowscape','luckychant','shadowsneak'],
 stages:[
  {name:'Feuforêve',types:['fantome'],base:st(60,60,60,85,85,85)},
  {name:'Magirêve',types:['fantome'],base:st(60,60,60,105,105,105)}]},
{id:'wobbuffet',abilities:['Marque Ombre','Télépathe'],moveIds:['amnesia','charm','counter','destinybond','encore','mirrorcoat','safeguard','splash'],
 stages:[
  {name:'Wynaut',types:['psy'],base:st(95,23,48,23,48,23)},
  {name:'Qulbutoké',types:['psy'],base:st(190,33,58,33,58,33)}]},
{id:'girafarig',abilities:['Attention','Matinal','Herbivore'],moveIds:['astonish','growl','tackle','confusion','stomp','psybeam','agility','crunch','batonpass','psychic','beatup','doublekick','futuresight','meanlook','mirrorcoat','takedown','uproar','wish','lowkick','confuseray','thief','facade','bulldoze','swift','endure','sunnyday','raindance','zenheadbutt','bodyslam','sleeptalk','reflect','lightscreen','dazzlinggleam','thunderwave','rest','imprison','skillswap','shadowball','hypervoice','thunderbolt','amnesia','calmmind','psychicterrain','earthquake','hyperbeam','thunder','psychup','doubleedge','endeavor','protect','trick','headbutt','mimic','dreameater','nightmare','snore','mudslap','swagger','irontail','magiccoat','recycle','signalbeam','shockwave','suckerpunch','stompingtantrum','razorwind','foresight','secretpower','psychicfangs','substitute','helpinghand','gravity','naturalgift','assurance','powerswap','guardswap','energyball','gigaimpact','nastyplot','trickroom','captivate','grassknot','chargebeam','doublehit','psyshock','telekinesis','foulplay','round','echoedvoice','storedpower','allyswitch','retaliate','workup','terablast','twinbeam','roar'],
 stages:[
  {name:'Girafarig',types:['normal','psy'],base:st(70,80,65,90,65,85)},
  {name:'Farigiraf',types:['normal','psy'],base:st(120,90,70,110,70,60),abilities:['Rumination','Queue Armure','Herbivore']}]},
{id:'pineco',abilities:['Fermeté','Envelocape'],moveIds:['bugbite','protect','selfdestruct','tackle','takedown','rapidspin','rollout','curse','spikes','explosion','irondefense','doubleedge','counter','flail','pinmissile','sandtomb','swift','facade','bulldoze','rocktomb','endure','sunnyday','raindance','sandstorm','dig','bodyslam','sleeptalk','reflect','lightscreen','rockblast','thunderwave','poisonjab','rest','rockslide','stealthrock','flashcannon','ironhead','gigadrain','earthquake','stoneedge','hyperbeam','solarbeam','painsplit','zapcannon','toxicspikes','headbutt','stringshot','mimic','defensecurl','snore','swagger','revenge','signalbeam','block','laserfocus','substitute','helpinghand','gravity','gyroball','naturalgift','payback','powertrick','seedbomb','bugbuzz','captivate','venoshock','round','strugglebug','drillrun','terablast','icespinner','pounce','magnetrise','rockpolish','earthpower','gigaimpact','mirrorshot','telekinesis','heavyslam','allyswitch','voltswitch','hardpress'],
 stages:[
  {name:'Kokiabo',types:['insecte'],base:st(50,65,90,35,35,15)},
  {name:'Foretress',types:['insecte','acier'],base:st(75,90,140,60,60,40)}]},
{id:'dunsparce',abilities:['Sérénité','Fuite','Phobique'],moveIds:['defensecurl','flail','mudslap','rollout','glare','screech','ancientpower','doubleedge','endeavor','aquatail','astonish','bite','curse','headbutt','takedown','agility','scaryface','protect','thief','facade','poisontail','bulldoze','mudshot','rocktomb','endure','sunnyday','raindance','sandstorm','dig','zenheadbutt','airslash','bodyslam','sleeptalk','poisonjab','rest','rockslide','shadowball','stealthrock','hypervoice','flamethrower','thunderbolt','amnesia','calmmind','icebeam','fireblast','blizzard','earthquake','stoneedge','hyperbeam','thunder','solarbeam','toxic','spite','uproar','yawn','hurricane','boomburst','bind','counter','thunderwave','mimic','dreameater','nightmare','snore','swagger','painsplit','irontail','psychup','magiccoat','shockwave','waterpulse','stompingtantrum','scaleshot','terrainpulse','skittersmack','dualwingbeat','rage','bide','secretpower','substitute','helpinghand','roost','gyroball','naturalgift','trumpcard','lastresort','dragonrush','earthpower','gigaimpact','captivate','chargebeam','coil','round','storedpower','hex','incinerate','retaliate','wildcharge','drillrun','terablast','icespinner','pounce','chillingwater','hyperdrill','tailwind','heavyslam','dragontail'],
 stages:[
  {name:'Insolourdo',types:['normal'],base:st(100,70,70,65,65,45)},
  {name:'Deusolourdo',types:['normal'],base:st(125,100,80,85,75,55)}]},
{id:'gligar',abilities:['Hyper Cutter','Voile Sable','Vaccin'],moveIds:['harden','poisonjab','sandattack','quickattack','furycutter','knockoff','nightslash','uturn','screech','crabhammer','swordsdance','takedown','agility','mudslap','scaryface','protect','thief','facade','poisontail','aerialace','bulldoze','metalclaw','swift','mudshot','rocktomb','endure','sunnyday','raindance','sandstorm','falseswipe','brickbreak','sleeptalk','rest','rockslide','taunt','spikes','darkpulse','crunch','stealthrock','batonpass','sludgebomb','earthquake','stoneedge','hyperbeam','poisonsting','slash','icefang','firefang','thunderfang','headbutt','doubleedge','counter','mimic','dreameater','snore','swagger','irontail','aquatail','bugbite','throatchop','razorwind','wingattack','sandtomb','skyattack','substitute','roost','naturalgift','feint','tailwind','payback','fling','powertrick','rockpolish','xscissor','earthpower','mudbomb','rockclimb','defog','crosspoison','gunkshot','captivate','honeclaws','venoshock','round','acrobatics','strugglebug','terablast','assurance','gigaimpact','powerwhip'],
 stages:[
  {name:'Scorplane',types:['sol','vol'],base:st(65,75,105,35,65,85)},
  {name:'Scorvol',types:['sol','vol'],base:st(75,95,125,45,75,95),abilities:['Hyper Cutter','Voile Sable','Soin Poison']}]},
{id:'snubbull',abilities:['Intimidation','Fuite','Phobique'],moveIds:['charm','growl','outrage','scaryface','tackle','tailwhip','bite','lick','headbutt','playrough','crunch','takedown','faketears','mudslap','protect','waterpulse','lowkick','thief','facade','bulldoze','rocktomb','endure','sunnyday','raindance','dig','brickbreak','bulkup','bodyslam','firepunch','thunderpunch','icepunch','sleeptalk','dazzlinggleam','metronome','thunderwave','rest','rockslide','taunt','shadowball','hypervoice','encore','flamethrower','thunderbolt','reversal','fireblast','sludgebomb','earthquake','stoneedge','overheat','focusblast','hyperbeam','thunder','closecombat','solarbeam','spite','superfang','uproar','focuspunch','doubleedge','endeavor','curse','icefang','firefang','thunderfang','megapunch','megakick','counter','seismictoss','mimic','defensecurl','snore','swagger','healbell','dynamicpunch','superpower','shockwave','leer','reflect','feintattack','present','smellingsalts','irontail','stompingtantrum','roar','substitute','helpinghand','naturalgift','payback','fling','lastresort','captivate','round','incinerate','retaliate','workup','wildcharge','snarl','terablast','temperflare','gigaimpact','rockclimb','lowsweep','covet'],
 stages:[
  {name:'Snubbull',types:['fee'],base:st(60,80,50,40,40,30)},
  {name:'Granbull',types:['fee'],base:st(90,120,75,60,60,45),abilities:['Intimidation','Pied Véloce','Phobique']}]},
{id:'qwilfish',abilities:['Point Poison','Glissade','Intimidation'],moveIds:['toxicspikes','poisonsting','tackle','harden','watergun','bubblebeam','haze','spikes','poisonjab','pinmissile','toxic','crunch','thunderwave','icebeam','protect','swordsdance','endure','waterpulse','mudshot','agility','selfdestruct','icywind','sludgebomb','doubleedge','whirlpool','surf','shadowball','curse','taunt','hydropump','waterfall','blizzard','facade','takedown','scaryface','poisontail','swift','reversal','raindance','sleeptalk','rest','spite','minimize','fellstinger','spitup','stockpile','aquatail','destinybond','headbutt','mimic','defensecurl','snore','rollout','swagger','painsplit','dive','signalbeam','bounce','shockwave','throatchop','liquidation','steelroller','scaleshot','supersonic','flail','astonish','barbbarrage','substitute','gyroball','brine','naturalgift','acupressure','payback','assurance','gigaimpact','gunkshot','captivate','aquajet','venoshock','sludgewave','acidspray','round','scald','hex','terablast','chillingwater'],
 stages:[
  {name:'Qwilfish',types:['eau','poison'],base:st(65,95,75,55,55,85)}]},
{id:'shuckle',abilities:['Fermeté','Gloutonnerie','Contestation'],moveIds:['withdraw','wrap','rollout','rockthrow','safeguard','rest','bugbite','rockslide','stickyweb','stoneedge','acid','defensecurl','infestation','knockoff','mudslap','rockblast','sweetscent','toxic','sunnyday','protect','earthquake','dig','doubleteam','sludgebomb','sandstorm','rocktomb','facade','attract','endure','flash','stealthrock','sleeptalk','bulldoze','swagger','strength','rocksmash','bind','headbutt','bodyslam','doubleedge','stringshot','mimic','snore','ancientpower','steelroller','meteorbeam','skittersmack','sandtomb','substitute','helpinghand','gyroball','naturalgift','acupressure','powertrick','gastroacid','rockpolish','earthpower','captivate','guardsplit','powersplit','venoshock','smackdown','sludgewave','afteryou','round','shellsmash','finalgambit','strugglebug','covet'],
 stages:[
  {name:'Caratroc',types:['insecte','roche'],base:st(20,10,230,10,230,5)}]},
{id:'heracross',abilities:['Essaim','Cran','Impudence'],moveIds:['leer','tackle','endure','pinmissile','detect','aerialace','takedown','brickbreak','rockblast','swordsdance','megahorn','closecombat','headbutt','rocksmash','bulkup','rockslide','protect','dig','bodyslam','nightslash','rocktomb','bulletseed','hyperbeam','knockoff','shadowclaw','stoneedge','earthquake','bulldoze','irondefense','spikes','curse','focusblast','facade','falseswipe','furyattack','hornattack','counter','thrash','doubleedge','flail','harden','seismictoss','lowkick','thief','sunnyday','raindance','sleeptalk','rest','reversal','bugbite','focuspunch','endeavor','armthrust','throatchop','mimic','snore','swagger','furycutter','coaching','bide','pursuit','revenge','substitute','helpinghand','naturalgift','feint','assurance','fling','bugbuzz','vacuumwave','gigaimpact','captivate','venoshock','smackdown','round','chipaway','circlethrow','retaliate','strugglebug','workup','terablast','pounce'],
 stages:[
  {name:'Scarhino',types:['insecte','combat'],base:st(80,125,75,40,95,85),forms:{
    scarhinoite:{name:'Méga-Scarhino',types:['insecte','combat'],base:st(80,185,115,40,105,75),abilities:['Multi-Coups']}
  }}]},
{id:'sneasel',abilities:['Attention','Regard Vif','Pickpocket'],moveIds:['agility','beatup','leer','quickattack','scratch','slash','taunt','metalclaw','icywind','furyswipes','screech','nightslash','darkpulse','bite','counter','fakeout','spite','takedown','faketears','scaryface','protect','waterpulse','lowkick','thief','facade','aerialace','swift','endure','sunnyday','raindance','dig','falseswipe','brickbreak','shadowclaw','icepunch','sleeptalk','metronome','poisonjab','rest','swordsdance','shadowball','surf','calmmind','reversal','icebeam','blizzard','focusblast','hyperbeam','knockoff','iciclespear','focuspunch','headbutt','doubleedge','mimic','defensecurl','dreameater','nightmare','snore','mudslap','swagger','furycutter','dynamicpunch','irontail','psychup','rocksmash','snatch','laserfocus','throatchop','lashout','tripleaxel','reflect','foresight','pursuit','assist','crushclaw','substitute','helpinghand','naturalgift','feint','payback','embargo','fling','punishment','xscissor','gigaimpact','nastyplot','avalanche','iceshard','psychocut','captivate','doublehit','honeclaws','lowsweep','foulplay','round','retaliate','snarl','iciclecrash','terablast','snowscape','assurance','icespinner','chillingwater'],
 stages:[
  {name:'Farfuret',types:['glace','tenebres'],base:st(55,95,55,35,75,115)},
  {name:'Dimoret',types:['tenebres','glace'],base:st(70,120,65,45,85,125),abilities:['Pression','Pickpocket']}]},
{id:'teddiursa',abilities:['Ramassage','Pied Véloce','Cherche Miel'],moveIds:['faketears','leer','lick','scratch','furyswipes','sweetscent','slash','playnice','playrough','scaryface','rest','snore','thrash','bellydrum','closecombat','counter','crosschop','crunch','doubleedge','furycutter','metalclaw','nightslash','seismictoss','yawn','takedown','charm','protect','lowkick','thief','facade','aerialace','bulldoze','swift','rocktomb','endure','sunnyday','raindance','dig','brickbreak','shadowclaw','bulkup','bodyslam','firepunch','thunderpunch','icepunch','sleeptalk','metronome','rockslide','taunt','swordsdance','hypervoice','earthquake','stoneedge','hyperbeam','uproar','focuspunch','headlongrush','babydolleyes','highhorsepower','megapunch','megakick','headbutt','mimic','defensecurl','mudslap','rollout','swagger','dynamicpunch','superpower','focusenergy','laserfocus','throatchop','stompingtantrum','roar','substitute','helpinghand','naturalgift','payback','fling','lastresort','seedbomb','avalanche','gunkshot','captivate','honeclaws','smackdown','round','chipaway','retaliate','workup','terablast','hammerarm','gigaimpact','rockclimb','drainpunch','vacuumwave','earthpower','heavyslam','hardpress','covet'],
 stages:[
  {name:'Teddiursa',types:['normal'],base:st(60,80,50,50,50,40)},
  {name:'Ursaring',types:['normal'],base:st(90,130,75,75,75,55),abilities:['Cran','Pied Véloce','Tension']},
  {name:'Ursaking',types:['sol','normal'],base:st(130,140,105,45,80,50),abilities:['Cran','Anti-Bombe','Tension']}]},
{id:'slugma',abilities:['Armumagma','Corps Ardent','Armure Rouillée'],moveIds:['ember','rockthrow','smog','yawn','harden','ancientpower','rockslide','amnesia','bodyslam','recover','flamethrower','takedown','mudslap','protect','firespin','facade','bulldoze','mudshot','rocktomb','endure','sunnyday','sandstorm','sleeptalk','reflect','lightscreen','rockblast','rest','irondefense','willowisp','stealthrock','heatwave','fireblast','earthquake','stoneedge','overheat','hyperbeam','solarbeam','curse','doubleedge','mimic','defensecurl','selfdestruct','snore','rollout','swagger','painsplit','smokescreen','acidarmor','stockpile','spitup','swallow','memento','stompingtantrum','substitute','naturalgift','guardswap','powergem','earthpower','lavaplume','captivate','smackdown','flameburst','flamecharge','afteryou','round','clearsmog','incinerate','inferno','heatcrash','terablast','temperflare','gyroball','flareblitz','rockpolish','gigaimpact','shellsmash'],
 stages:[
  {name:'Limagma',types:['feu'],base:st(40,40,40,70,40,20)},
  {name:'Volcaropod',types:['feu','roche'],base:st(60,50,120,90,80,30)}]},
{id:'swinub',abilities:['Benêt','Rideau Neige','Isograisse'],moveIds:['ancientpower','flail','icefang','mudslap','powdersnow','tackle','mist','endure','icywind','amnesia','takedown','earthquake','blizzard','thrash','charm','scaryface','protect','facade','bulldoze','mudshot','rocktomb','raindance','sandstorm','dig','bodyslam','sleeptalk','reflect','rockblast','rest','rockslide','ironhead','stealthrock','reversal','icebeam','stoneedge','hyperbeam','haze','knockoff','iciclespear','doubleedge','endeavor','curse','headbutt','mimic','defensecurl','snore','swagger','superpower','bite','fissure','freezedry','stompingtantrum','furycutter','block','roar','substitute','mudsport','naturalgift','earthpower','avalanche','iceshard','mudbomb','captivate','smackdown','round','iciclecrash','terablast','snowscape','gigaimpact','rockclimb','doublehit','heavyslam','hardpress'],
 stages:[
  {name:'Marcacrin',types:['glace','sol'],base:st(50,50,40,30,30,50)},
  {name:'Cochignon',types:['glace','sol'],base:st(100,100,80,60,60,50)},
  {name:'Mammochon',types:['glace','sol'],base:st(110,130,80,70,60,80)}]},
{id:'corsola',abilities:['Agitation','Médic Nature','Régé-Force'],moveIds:['harden','tackle','watergun','endure','ancientpower','bubblebeam','flail','recover','mirrorcoat','amnesia','confuseray','curse','iciclespear','ingrain','mist','screech','waterpulse','calmmind','sunnyday','icebeam','blizzard','lightscreen','protect','raindance','safeguard','earthquake','dig','psychic','shadowball','doubleteam','reflect','sandstorm','rocktomb','facade','rest','attract','stoneedge','stealthrock','rockslide','sleeptalk','bulldoze','swagger','surf','strength','rocksmash','lifedew','headbutt','bodyslam','doubleedge','mimic','defensecurl','selfdestruct','explosion','snore','mudslap','icywind','rollout','magiccoat','endeavor','irondefense','suckerpunch','throatchop','stompingtantrum','liquidation','meteorbeam','barrier','bide','camouflage','substitute','brine','naturalgift','luckychant','aquaring','rockpolish','powergem','earthpower','captivate','headsmash','round','scald'],
 stages:[
  {name:'Corayon',types:['eau','roche'],base:st(65,55,95,65,95,35)}]},
{id:'remoraid',abilities:['Agitation','Sniper','Lunatique'],moveIds:['octazooka','waterpulse','icebeam','hydropump','hyperbeam','flamethrower','flashcannon','focusenergy','icywind','psychic','rest','sludgebomb','swift','watergun','bubble','aurorabeam','lockon','signalbeam','protect','toxic','raindance','whirlpool','waterfall','doubleedge','sleeptalk','mudslap','endure','stringshot','thunderwave','mimic','defensecurl','snore','swagger','dive','bounce','supersonic','screech','haze','flail','mudshot','rockblast','bind','seismictoss','skittersmack','substitute','helpinghand','waterspout','brine','naturalgift','assurance','seedbomb','gunkshot','captivate','chargebeam','smackdown','soak','acidspray','entrainment','round','scald','incinerate','payback','wringout','energyball','gigaimpact','sludgewave'],
 stages:[
  {name:'Rémoraid',types:['eau'],base:st(35,65,35,65,35,65)},
  {name:'Octillery',types:['eau'],base:st(75,105,75,105,75,45),abilities:['Ventouse','Sniper','Lunatique']}]},
{id:'delibird',abilities:['Esprit Vital','Agitation','Insomnia'],moveIds:['icywind','aerialace','airslash','featherdance','icepunch','freezedry','blizzard','brickbreak','icebeam','protect','swift','bodyslam','endure','waterpulse','fly','hyperbeam','agility','spikes','facade','iciclespear','present','drillpeck','aurorabeam','counter','destinybond','memento','quickattack','rapidspin','splash','takedown','thief','aircutter','raindance','sleeptalk','rest','reversal','haze','focuspunch','weatherball','endeavor','megapunch','megakick','headbutt','doubleedge','seismictoss','mimic','skyattack','snore','mudslap','rollout','swagger','recycle','signalbeam','bounce','tripleaxel','dualwingbeat','futuresight','fakeout','iceball','auroraveil','substitute','helpinghand','naturalgift','pluck','tailwind','assurance','fling','seedbomb','bravebird','gigaimpact','avalanche','iceshard','defog','gunkshot','captivate','foulplay','round','acrobatics','bestow','frostbreath','drillrun','terablast','icespinner','snowscape','chillingwater'],
 stages:[
  {name:'Cadoizo',types:['glace','vol'],base:st(45,55,45,65,45,75)}]},
{id:'mantine',abilities:['Glissade','Absorbe-Eau','Ignifu-Voile'],moveIds:['tackle','aerialace','waterpulse','airslash','hydropump','doubleedge','aquatail','bulldoze','hyperbeam','icebeam','icywind','ironhead','rest','rockslide','swift','watergun','bubble','wingattack','twister','watersport','confuseray','agility','waterfall','hurricane','protect','toxic','raindance','whirlpool','aircutter','sleeptalk','mudslap','endure','amnesia','headbutt','snore','dive','signalbeam','bounce','slam','haze','splash','mirrorcoat','bodyslam','stringshot','mimic','swagger','liquidation','dualwingbeat','substitute','helpinghand','mudsport','roost','naturalgift','tailwind','aquaring','captivate','wideguard','round','scald','acrobatics','brine','assurance','seedbomb','gigaimpact','defog','gunkshot'],
 stages:[
  {name:'Babimanta',types:['eau','vol'],base:st(45,20,50,60,120,50)},
  {name:'Démanta',types:['eau','vol'],base:st(65,40,70,80,140,70)}]},
{id:'skarmory',abilities:['Regard Vif','Fermeté','Armure Rouillée'],moveIds:['leer','peck','metalclaw','sandtomb','wingattack','slash','steelwing','nightslash','stridoson','spikes','irondefense','airslash','rockslide','protect','aerialace','swift','swordsdance','doubleteam','endure','rocktomb','stealthrock','fly','hyperbeam','agility','ironhead','hurricane','flashcannon','darkpulse','curse','whirlwind','taunt','facade','skyattack','sandattack','furyattack','drillpeck','aircutter','takedown','thief','icywind','sleeptalk','rest','reversal','doubleedge','counter','mimic','snore','mudslap','swagger','furycutter','twister','steelbeam','dualwingbeat','pursuit','roar','substitute','roost','naturalgift','feint','pluck','tailwind','payback','assurance','guardswap','xscissor','bravebird','gigaimpact','defog','captivate','ominouswind','round','skydrop','drillrun','terablast'],
 stages:[
  {name:'Airmure',types:['acier','vol'],base:st(65,80,140,40,70,70),forms:{
    skarmorite:{name:'Méga-Airmure',types:['acier','vol'],base:st(65,140,110,40,100,110),abilities:["Nerfs d'Acier"]}
  }}]},
{id:'houndour',abilities:['Matinal','Torche','Tension'],moveIds:['ember','leer','bite','takedown','darkpulse','flamethrower','crunch','overheat','headbutt','toxic','protect','bodyslam','endure','fireblast','hyperbeam','mudshot','sludgebomb','doubleedge','willowisp','heatwave','hypervoice','firespin','shadowball','taunt','facade','torment','swagger','howl','smog','beatup','counter','destinybond','reversal','spite','suckerpunch','mudslap','scaryface','thief','sleeptalk','rest','sunnyday','raindance','superfang','endeavor','throatchop','lashout','comeuppance','firefang','thunderfang','mimic','swift','dreameater','nightmare','snore','irontail','uproar','roleplay','snatch','rage','pursuit','laserfocus','roar','substitute','helpinghand','naturalgift','feint','payback','embargo','punishment','flareblitz','nastyplot','captivate','flamecharge','foulplay','round','incinerate','retaliate','inferno','snarl','terablast','temperflare','gigaimpact'],
 stages:[
  {name:'Malosse',types:['tenebres','feu'],base:st(45,60,30,80,50,65)},
  {name:'Démolosse',types:['tenebres','feu'],base:st(75,90,50,110,80,95),forms:{
    demolossite:{name:'Méga-Démolosse',types:['tenebres','feu'],base:st(75,90,90,140,90,115),abilities:['Force Soleil']}
  }}]},
{id:'phanpy',abilities:['Ramassage','Voile Sable'],moveIds:['bulldoze','defensecurl','growl','hornattack','rapidspin','rollout','knockoff','slam','scaryface','earthquake','furyattack','ancientpower','bodyslam','counter','endeavor','fissure','focusenergy','playrough','snore','takedown','charm','mudslap','protect','icefang','thief','facade','mudshot','rocktomb','endure','sunnyday','raindance','sandstorm','dig','sleeptalk','poisonjab','rest','rockslide','ironhead','irondefense','stealthrock','hypervoice','encore','stoneedge','hyperbeam','curse','doubleedge','highhorsepower','stompingtantrum','tackle','flail','firefang','thunderfang','headbutt','mimic','swagger','irontail','superpower','watergun','block','bounce','roar','substitute','helpinghand','naturalgift','lastresort','seedbomb','earthpower','iceshard','gunkshot','captivate','headsmash','smackdown','heavyslam','round','echoedvoice','terablast','gyroball','assurance','rockpolish','gigaimpact','icespinner'],
 stages:[
  {name:'Phanpy',types:['sol'],base:st(90,60,60,40,40,40)},
  {name:'Donphan',types:['sol'],base:st(90,120,120,60,60,50),abilities:['Fermeté','Voile Sable']}]},
{id:'stantler',abilities:['Intimidation','Fouille','Herbivore'],moveIds:['tackle','leer','astonish','hypnosis','stomp','sandattack','takedown','confuseray','calmmind','zenheadbutt','imprison','doubleedge','bite','disable','doublekick','extrasensory','megahorn','spite','thrash','agility','scaryface','protect','psybeam','thief','facade','bulldoze','swift','endure','sunnyday','raindance','dig','bodyslam','sleeptalk','reflect','lightscreen','thunderwave','rest','skillswap','trick','shadowball','psychic','thunderbolt','earthquake','hyperbeam','thunder','solarbeam','uproar','psychup','futuresight','curse','psyshieldbash','roleplay','headbutt','mimic','dreameater','nightmare','snore','mudslap','swagger','irontail','signalbeam','bounce','shockwave','suckerpunch','throatchop','rage','roar','substitute','helpinghand','mudsport','gravity','naturalgift','mefirst','lastresort','energyball','earthpower','gigaimpact','trickroom','captivate','chargebeam','psyshock','magicroom','entrainment','round','storedpower','retaliate','workup','wildcharge','terablast'],
 stages:[
  {name:'Cerfrousse',types:['normal'],base:st(73,95,62,85,65,85)},
  {name:'Cerbyllin',types:['normal','psy'],base:st(103,105,72,105,75,65)}]},
{id:'smeargle',abilities:['Tempo Perso','Technicien','Lunatique'],moveIds:['sketch'],
 stages:[
  {name:'Queulorior',types:['normal'],base:st(55,20,35,20,45,75)}]},
{id:'tyrogue',abilities:['Cran','Impassible','Esprit Vital'],moveIds:['fakeout','focusenergy','tackle','counter','highjumpkick','machpunch','rapidspin','takedown','protect','lowkick','thief','facade','bulldoze','swift','endure','sunnyday','raindance','brickbreak','bulkup','bodyslam','sleeptalk','rest','rockslide','uproar','doublekick','megakick','reversal','blazekick','closecombat','suckerpunch','axekick','megapunch','firepunch','icepunch','thunderpunch','agility','detect','focuspunch','dig','quickattack','triplekick','endeavor','headbutt','doubleedge','seismictoss','mimic','snore','mudslap','swagger','roleplay','laserfocus','mindreader','pursuit','metronome','dynamicpunch','superpower','knockoff','bounce','stompingtantrum','coaching','throatchop','rollout','twister','tripleaxel','substitute','helpinghand','naturalgift','feint','vacuumwave','bulletpunch','captivate','lowsweep','round','allyswitch','retaliate','workup','terablast','fling','gigaimpact','rockclimb','wideguard','drainpunch','quickguard','gyroball','drillrun','icespinner','covet'],
 stages:[
  {name:'Debugant',types:['combat'],base:st(35,35,35,35,35,35)}], branches:[
  {name:'Kicklee',types:['combat'],base:st(50,120,53,35,110,87),abilities:['Échauffement','Téméraire','Délestage'],extraMoveIds:['highjumpkick','submission','rockslide']},
  {name:'Tygnon',types:['combat'],base:st(50,105,79,35,110,76),abilities:['Regard Vif','Poing de Fer','Attention'],extraMoveIds:['firepunch','icepunch','thunderpunch','submission']},
  {name:'Kapoera',types:['combat'],base:st(50,95,95,35,110,70),abilities:['Intimidation','Technicien','Impassible'],extraMoveIds:['brickbreak']}
 ]},
{id:'smoochum',abilities:['Benêt','Prédiction','Hydratation'],moveIds:['lick','pound','powdersnow','sweetkiss','confusion','sing','faketears','icepunch','psychic','lovelykiss','meanlook','perishsong','blizzard','fakeout','wish','waterpulse','calmmind','icebeam','lightscreen','protect','raindance','shadowball','doubleteam','reflect','facade','rest','attract','thief','skillswap','endure','recycle','flash','psychup','sleeptalk','dreameater','swagger','megapunch','megakick','bodyslam','doubleedge','counter','seismictoss','mimic','metronome','nightmare','snore','mudslap','icywind','healbell','dynamicpunch','uproar','trick','roleplay','magiccoat','signalbeam','zenheadbutt','meditate','substitute','helpinghand','miracleeye','wakeupslap','naturalgift','payback','fling','luckychant','copycat','nastyplot','avalanche','trickroom','captivate','grassknot','wonderroom','psyshock','magicroom','round','echoedvoice','storedpower','frostbreath','heartstamp','covet'],
 stages:[
  {name:'Lippouti',types:['glace','psy'],base:st(45,30,15,85,65,65)}]},
{id:'miltank',abilities:['Isograisse','Querelleur','Herbivore'],moveIds:['growl','tackle','rollout','defensecurl','stomp','healbell','headbutt','zenheadbutt','milkdrink','bodyslam','playrough','charm','belch','curse','doubleedge','present','reversal','seismictoss','focuspunch','waterpulse','sunnyday','icebeam','blizzard','hyperbeam','protect','raindance','solarbeam','irontail','thunderbolt','thunder','earthquake','shadowball','brickbreak','doubleteam','shockwave','sandstorm','rocktomb','facade','rest','attract','focusblast','endure','thunderwave','stealthrock','psychup','rockslide','sleeptalk','bulldoze','swagger','surf','strength','rocksmash','highhorsepower','firepunch','icepunch','thunderpunch','megapunch','megakick','counter','mimic','metronome','snore','mudslap','icywind','dynamicpunch','block','ironhead','stompingtantrum','steelroller','dizzypunch','substitute','helpinghand','wakeupslap','hammerarm','gyroball','naturalgift','fling','punishment','gigaimpact','captivate','heavyslam','afteryou','round','echoedvoice','retaliate','workup','heartstamp'],
 stages:[
  {name:'Écrémeuh',types:['normal'],base:st(95,80,105,40,70,100)}]},
{id:'raikou',abilities:['Pression','Attention'],moveIds:['charge','extremespeed','leer','quickattack','thundershock','spark','bite','calmmind','howl','crunch','extrasensory','discharge','reflect','raindance','thunder','zapcannon','takedown','agility','mudslap','scaryface','protect','facade','swift','endure','sunnyday','sandstorm','bodyslam','sleeptalk','lightscreen','thunderwave','rest','eerieimpulse','ironhead','aurasphere','shadowball','thunderbolt','electricterrain','hyperbeam','weatherball','doubleedge','thunderfang','headbutt','mimic','snore','swagger','irontail','psychup','signalbeam','shockwave','laserfocus','throatchop','risingvoltage','roar','substitute','helpinghand','naturalgift','magnetrise','gigaimpact','rockclimb','chargebeam','electroball','round','scald','quash','voltswitch','electroweb','wildcharge','snarl','terablast'],
 stages:[
  {name:'Raikou',types:['electrik'],base:st(90,85,75,115,100,115)}]},
{id:'entei',abilities:['Pression','Attention'],moveIds:['ember','leer','smokescreen','stomp','flamewheel','bite','calmmind','crunch','extrasensory','swagger','sunnyday','fireblast','eruption','extremespeed','sacredfire','takedown','agility','protect','firespin','facade','bulldoze','swift','endure','raindance','sandstorm','dig','bodyslam','sleeptalk','rest','ironhead','willowisp','shadowball','heatwave','flamethrower','reversal','stoneedge','overheat','hyperbeam','solarbeam','weatherball','doubleedge','scaryface','firefang','headbutt','mimic','snore','mudslap','irontail','psychup','laserfocus','stompingtantrum','scorchingsands','roar','substitute','helpinghand','naturalgift','flareblitz','gigaimpact','rockclimb','lavaplume','flamecharge','round','incinerate','quash','snarl','terablast'],
 stages:[
  {name:'Entei',types:['feu'],base:st(115,115,85,90,75,100)}]},
{id:'suicune',abilities:['Pression','Attention'],moveIds:['gust','leer','mist','watergun','waterpulse','bite','calmmind','icefang','crunch','extrasensory','surf','mirrorcoat','raindance','hydropump','blizzard','extremespeed','sheercold','takedown','agility','protect','facade','swift','icywind','endure','sandstorm','airslash','bodyslam','sleeptalk','waterfall','rest','ironhead','shadowball','icebeam','hyperbeam','weatherball','doubleedge','whirlpool','headbutt','mimic','snore','mudslap','swagger','irontail','psychup','dive','signalbeam','laserfocus','roar','substitute','helpinghand','brine','naturalgift','tailwind','gigaimpact','avalanche','rockclimb','ominouswind','round','scald','quash','snarl','terablast','snowscape','chillingwater'],
 stages:[
  {name:'Suicune',types:['eau'],base:st(100,75,115,90,115,85)}]},
{id:'larvitar',abilities:['Cran','Voile Sable'],moveIds:['leer','tackle','rockthrow','bite','sandtomb','rockslide','screech','crunch','earthquake','stoneedge','rockblast','hyperbeam','darkpulse','irondefense','dragonclaw','thunderwave','brickbreak','icebeam','protect','aerialace','thunderpunch','icepunch','firepunch','bodyslam','endure','rocktomb','stealthrock','fireblast','knockoff','mudshot','doubleedge','ironhead','shadowclaw','flamethrower','thunderbolt','curse','outrage','taunt','hydropump','blizzard','thunder','facade','ancientpower','swagger','muddywater','dragonpulse','bulldoze','dig','scaryface','thrash','sandstorm','icywind','sunnyday','raindance','sleeptalk','rest','dragondance','focusblast','focuspunch','spite','stompingtantrum','icefang','firefang','thunderfang','headbutt','mimic','snore','mudslap','irontail','uproar','superpower','stomp','focusenergy','pursuit','megapunch','megakick','lowkick','counter','seismictoss','nightmare','furycutter','dynamicpunch','block','shockwave','waterpulse','aquatail','lashout','substitute','helpinghand','naturalgift','payback','assurance','rockpolish','earthpower','gigaimpact','captivate','smackdown','round','chipaway','retaliate','snarl','terablast','roar','fling','powergem','avalanche','rockclimb','honeclaws','heavyslam','foulplay','incinerate','dragontail','hardpress'],
 stages:[
  {name:'Embrylex',types:['roche','sol'],base:st(50,64,50,45,50,41)},
  {name:'Ymphect',types:['roche','sol'],base:st(70,84,70,65,70,51),abilities:['Mue']},
  {name:'Tyranocif',types:['roche','tenebres'],base:st(100,134,110,95,100,61),abilities:['Sable Volant','Tension'],forms:{
    tyranocivite:{name:'Méga-Tyranocif',types:['roche','tenebres'],base:st(100,164,150,95,120,71),abilities:['Sable Volant']}
  }}]},
{id:'lugia',abilities:['Pression','Multi-Écaille'],moveIds:['ancientpower','gust','weatherball','whirlwind','mist','safeguard','calmmind','extrasensory','recover','aeroblast','raindance','hydropump','futuresight','skyattack','takedown','scaryface','protect','waterpulse','facade','aerialace','swift','icywind','aircutter','endure','sunnyday','sandstorm','zenheadbutt','airslash','bodyslam','sleeptalk','reflect','lightscreen','waterfall','rest','imprison','fly','skillswap','ironhead','trick','gigadrain','shadowball','dragonpulse','hypervoice','psychic','surf','thunderbolt','icebeam','blizzard','earthquake','hurricane','hyperbeam','thunder','psychup','doubleedge','whirlpool','curse','headbutt','thunderwave','mimic','dreameater','nightmare','snore','mudslap','swagger','irontail','twister','dive','signalbeam','shockwave','aquatail','laserfocus','scaleshot','dualwingbeat','roar','substitute','helpinghand','roost','brine','naturalgift','tailwind','punishment','dragonrush','bravebird','earthpower','gigaimpact','avalanche','defog','chargebeam','ominouswind','wonderroom','psyshock','telekinesis','round','echoedvoice','skydrop','acrobatics','dragontail','terablast','chillingwater'],
 stages:[
  {name:'Lugia',types:['psy','vol'],base:st(106,90,130,90,154,110)}]},
{id:'hooh',abilities:['Pression','Régé-Force'],moveIds:['ancientpower','gust','weatherball','whirlwind','safeguard','calmmind','extrasensory','recover','sacredfire','sunnyday','fireblast','futuresight','skyattack','overheat','takedown','protect','firespin','facade','aerialace','swift','aircutter','endure','raindance','sandstorm','zenheadbutt','airslash','bodyslam','sleeptalk','reflect','lightscreen','rest','imprison','fly','ironhead','willowisp','gigadrain','shadowball','hypervoice','heatwave','psychic','flamethrower','thunderbolt','earthquake','hurricane','hyperbeam','thunder','solarbeam','psychup','doubleedge','lifedew','thunderwave','mimic','dreameater','nightmare','snore','mudslap','swagger','twister','signalbeam','shockwave','laserfocus','dualwingbeat','scorchingsands','roar','substitute','helpinghand','roost','naturalgift','pluck','tailwind','punishment','flareblitz','bravebird','earthpower','gigaimpact','defog','chargebeam','ominouswind','flamecharge','round','echoedvoice','skydrop','incinerate','terablast'],
 stages:[
  {name:'Ho-Oh',types:['feu','vol'],base:st(106,130,90,110,154,90)}]},
{id:'celebi',abilities:['Médic Nature'],moveIds:['confusion','healbell','magicalleaf','batonpass','ancientpower','recover','futuresight','waterpulse','calmmind','sunnyday','hyperbeam','lightscreen','protect','raindance','gigadrain','safeguard','dazzlinggleam','solarbeam','psychic','shadowball','doubleteam','reflect','shockwave','sandstorm','aerialace','facade','rest','skillswap','endure','thunderwave','swordsdance','stealthrock','psychup','sleeptalk','dreameater','swagger','uturn','cut','perishsong','lifedew','doubleedge','mimic','defensecurl','metronome','swift','nightmare','snore','mudslap','synthesis','uproar','trick','magiccoat','signalbeam','suckerpunch','zenheadbutt','laserfocus','expandingforce','grassyglide','dualwingbeat','leechseed','substitute','helpinghand','healingwish','naturalgift','fling','healblock','lastresort','worryseed','seedbomb','energyball','earthpower','gigaimpact','nastyplot','psychocut','trickroom','leafstorm','grassknot','chargebeam','wonderroom','telekinesis','magicroom','round','echoedvoice','allyswitch'],
 stages:[
  {name:'Celebi',types:['psy','plante'],base:st(100,100,100,100,100,100)}]},
{id:'unown',abilities:['Lévitation','Annule Garde'],moveIds:['hiddenpower'],
 stages:[
  {name:'Zarbi',types:['psy'],base:st(48,72,48,72,48,48)}]},

];

const DEX_NUMBERS_GEN2 = {
  'Germignon':152,'Macronium':153,'Méganium':154,
  'Héricendre':155,'Feurisson':156,'Typhlosion':157,
  'Kaiminus':158,'Crocrodil':159,'Aligatueur':160,
  'Fouinette':161,'Fouinar':162,
  'Hoothoot':163,'Noarfang':164,
  'Coxy':165,'Coxyclaque':166,
  'Mimigal':167,'Migalos':168,
  'Loupio':170,'Lanturn':171,
  'Togepi':175,'Togetic':176,'Togekiss':468,
  'Natu':177,'Xatu':178,
  'Wattouat':179,'Lainergie':180,'Pharamp':181,
  'Marill':183,'Azumarill':184,
  'Manzaï':438,'Simularbre':185,
  'Granivol':187,'Floravol':188,'Cotovol':189,
  'Capumain':190,'Capidextre':424,
  'Tournegrin':191,'Héliatronc':192,
  'Yanma':193,'Yanmega':469,
  'Axoloto':194,'Maraiste':195,
  'Cornèbre':198,'Corboss':430,
  'Feuforêve':200,'Magirêve':429,
  'Zarbi':201,
  'Qulbutoké':202,
  'Girafarig':203,
  'Kokiabo':204,'Foretress':205,
  'Insolourdo':206,
  'Scorplane':207,'Scorvol':472,
  'Snubbull':209,'Granbull':210,
  'Qwilfish':211,
  'Caratroc':213,
  'Scarhino':214,
  'Farfuret':215,'Dimoret':461,
  'Teddiursa':216,'Ursaring':217,'Ursaking':901,
  'Limagma':218,'Volcaropod':219,
  'Marcacrin':220,'Cochignon':221,'Mammochon':473,
  'Corayon':222,
  'Rémoraid':223,'Octillery':224,
  'Cadoizo':225,
  'Babimanta':458,'Démanta':226,
  'Airmure':227,
  'Malosse':228,'Démolosse':229,
  'Phanpy':231,'Donphan':232,
  'Cerfrousse':234,'Cerbyllin':899,
  'Queulorior':235,
  'Debugant':236,
  'Kapoera':237,
  'Écrémeuh':241,
  'Raikou':243,
  'Entei':244,
  'Suicune':245,
  'Embrylex':246,'Ymphect':247,'Tyranocif':248,
  'Lugia':249,
  'Ho-Oh':250,
  'Celebi':251,
  'Farigiraf':981,'Deusolourdo':982,
};
