/* ==== pokemon/index.js : fusionne les 5 générations en LINES / DEX_NUMBERS ==== */
const LINES = [...LINES_GEN1, ...LINES_GEN2, ...LINES_GEN3, ...LINES_GEN4, ...LINES_GEN5, ...LINES_GEN6];
const DEX_NUMBERS = Object.assign({}, DEX_NUMBERS_GEN1, DEX_NUMBERS_GEN2, DEX_NUMBERS_GEN3, DEX_NUMBERS_GEN4, DEX_NUMBERS_GEN5, DEX_NUMBERS_GEN6);
